export const worldNames = [
  "Debug",
  "ISLAND-GUILD-0001a_ISL_DL_T1_NON",
  "ISLAND-PLAYER-0001a_ISL_DL_T1_NON",
  "ISLAND-PLAYER-0001f_ISL_DL_T1_NON",
  "ISLAND-PLAYER-0001e_ISL_DL_T1_NON",
  "ISLAND-PLAYER-0001d_ISL_DL_T1_NON",
  "ISLAND-PLAYER-0001c_ISL_DL_T1_NON",
  "ISLAND-PLAYER-0001b_ISL_DL_T1_NON",
  "ISLAND-GUILD-0001b_ISL_DL_T1_NON",
  "ISLAND-GUILD-0001c_ISL_DL_T1_NON",
  "ISLAND-GUILD-0001d_ISL_DL_T1_NON",
  "ISLAND-GUILD-0001e_ISL_DL_T1_NON",
  "ISLAND-GUILD-0001f_ISL_DL_T1_NON",
  "Swamp Cross",
  "Tharcal Fissure",
  "Mushroom Cave",
  "Mushroom Cave",
  "Fishy Business",
  "Fishy Business",
  "Stone Wars",
  "Stone Wars",
  "Cairn Darg",
  "Gwan Gorge",
  "Malag Crevasse",
  "Creag Morr",
  "Cairn Camain",
  "Cairn Glascore",
  "Pen Gent",
  "Pen Garn",
  "Crose Gorge",
  "Birken Fell",
  "Eldon Hill",
  "Lewsdon Hill",
  "Blackthorn Quarry",
  "Haytor",
  "Brent Knoll",
  "Mase Knoll",
  "Croker Hill",
  "Goffers Knoll",
  "Vixen Tor",
  "Prospector's Hope",
  "Steelhide Meadow",
  "Longmarch Meadow",
  "Lazygrass Plain",
  "Snapshaft Trough",
  "Drywater Meadow",
  "Parchthroat Plain",
  "Deadvein Gully",
  "Roastcorpse Steppe",
  "Kindlegrass Steppe",
  "Ferndell",
  "Wyre Forest",
  "Stagbourne",
  "Murkweald",
  "Longtimber Glen",
  "Birchcopse",
  "Willow Wood",
  "Oakcopse",
  "Rowanwood",
  "Larchroad",
  "Pen Kerrig",
  "Slimehag",
  "Bonepool Marsh",
  "Spectral Sump",
  "Willowsigh Marsh",
  "Stumprot Swamp",
  "Dusklight Fen",
  "Dewleaf Fen",
  "Stinkhag",
  "Chillhag",
  "Slowtree Plain",
  "Smoothfloor Cleft",
  "Gutras Hill",
  "Mardale",
  "Wispwhisper Marsh",
  "Curlew Fen",
  "Saddle Tor",
  "Windripple Fen",
  "Mawar Gorge",
  "Russerdell",
  "Bryn Gorge",
  "Cairn Gorm",
  "Lumber Lunacy",
  "Preaching to the Dead",
  "Preaching to the Dead",
  "Bowscale Fell",
  "Cairn Fidair",
  "Creag Garr",
  "Nightcreak Marsh",
  "Fractured Ground",
  "Cracked Earth",
  "Redlake",
  "Yew Wood",
  "Highbole Glen",
  "Hornbeam Wood",
  "Steppe Cross",
  "Highland Cross",
  "Haldon Tor",
  "Lumber Lunacy",
  "Martlock",
  "Fort Sterling",
  "Forest Cross",
  "Mountain Cross",
  "Thetford",
  "Sleetwater Basin",
  "Lymhurst",
  "Camlann",
  "Astolat",
  "Curious Excavation",
  "Lurking Underneath",
  "Bridgewatch",
  "Rock Adit",
  "Sabertooth Den",
  "Swamp Burrow",
  "Ore Adit",
  "Forest Burrow",
  "The Underway",
  "Caerleon",
  "Runnel Sink",
  "Inis Mon",
  "Three Sisters",
  "A Fistful of Silver",
  "Cedarcopse",
  "Bellever Tor",
  "Pen Uchaf",
  "Shiftshadow Expanse",
  "Caerleon Market",
  "Bank of Caerleon",
  "Eternal Battle",
  "Lurking Underneath",
  "Arena1",
  "Arena2",
  "The Arena",
  "Preaching to the Dead",
  "Bank of Thetford",
  "Thetford Market",
  "Bank of Lymhurst",
  "Lymhurst Market",
  "Bank of Bridgewatch",
  "Bridgewatch Market",
  "Bank of Martlock",
  "Martlock Market",
  "Bank of Fort Sterling",
  "Fort Sterling Market",
  "Eternal Battle",
  "Fishy Business",
  "Lumber Lunacy",
  "Mushroom Cave",
  "Lurking Underneath",
  "Stone Wars",
  "Three Sisters",
  "A Fistful Of Silver",
  "In the Raven's Claws",
  "In the Raven's Claws",
  "Farmland Skirmish",
  "HomeTerritory Skirmish",
  "Resource Skirmish",
  "Resource Skirmish",
  "Resource Skirmish 2",
  "Crystal Realm",
  "Crystal Realm",
  "The Lighthouse",
  "Forgotten Woods",
  "Mountain Fort",
  "The Cove",
  "Caerleon Market",
  "ARENA-City",
  "HIDEOUT",
  "HIDEOUT",
  "HIDEOUT",
  "Northstrand Dunes",
  "Northstrand Beach",
  "Scuttlesink Mouth",
  "Deepwood Dell",
  "Whitebank Stream",
  "Whitebank Shore",
  "Whitebank Cross",
  "Whitebank Wall",
  "Meltwater Bog",
  "Whitebank Descent",
  "Whitebank Ridge",
  "Timberslope Dell",
  "Deepwood Pines",
  "Frostpeak Vista",
  "Frostpeak Ascent",
  "Floatshoal Fissure",
  "Floatshoal Bight",
  "Darkseep Core",
  "Meltwater Delta",
  "Meltwater Sump",
  "Skysand Plateau",
  "Everwinter Crossing",
  "Everwinter Plain",
  "Everwinter Gorge",
  "Scuttlesink Marsh",
  "Brambleshore Hinterlands",
  "Shaleheath Steep",
  "Everwinter Reach",
  "Everwinter Peak",
  "Everwinter Passage",
  "Everwinter Expanse",
  "Everwinter Incline",
  "Stoneslip Passage",
  "Whitecap Cave",
  "Scuttlesink Pools",
  "Timbertop Dale",
  "Timbertop Wood",
  "Timbertop Escarp",
  "Shaleheath Hills",
  "Everwinter Shores",
  "Wetgrave Bog",
  "Wetgrave Swale",
  "Wetgrave Marsh",
  "Timberslope Grove",
  "Timberslope Bridge",
  "Swiftsands Plain",
  "Drybasin Riverbed",
  "Swiftsands Basin",
  "Swiftsands Chaparral",
  "Skylake Bridge",
  "Greenshore Bay",
  "Flatrock Cliffs",
  "Skullmarsh Lower",
  "Skullmarsh Upper",
  "Greenshore Peninsula",
  "Giantweald Dale",
  "Watchwood Precipice",
  "Watchwood Grove",
  "Giantweald Woods",
  "Watchwood Lakeside",
  "Watchwood Bluffs",
  "Giantweald Edge",
  "Slakesands Canyon",
  "Drybasin Oasis",
  "Slakesands Mesa",
  "Flatrock Plateau",
  "Munten Rise",
  "Munten Tundra",
  "Munten Fell",
  "Hightree Steep",
  "Hightree Lake",
  "Hightree Dale",
  "Hightree Strand",
  "Hightree Glade",
  "Hightree Enclave",
  "Hightree Pass",
  "Hightree Levee",
  "Hightree Cliffs",
  "Hightree Isle",
  "Hightree Hillock",
  "Glacierbreak Summit",
  "Drownfield Course",
  "Widemoor Shore",
  "Widemoor Pool",
  "Willowshade Wetlands",
  "Widemoor Estuary",
  "Widemoor Hills",
  "Drownfield Wetland",
  "Widemoor End",
  "Willowshade Pools",
  "Widemoor Woods",
  "Willowshade Hills",
  "Timberscar Dell",
  "Timberscar Copse",
  "Drytop Riverbed",
  "Drytop Pillars",
  "Stalagmite Adit",
  "Drownfield Mire",
  "Drownfield Fen",
  "Drownfield Slough",
  "Drownfield Rut",
  "Drownfield Quag",
  "Meltwater Channel",
  "Drownfield Sink",
  "Deadpine Forest",
  "Skysand Ridge",
  "Citadel of Ash",
  "Glacierfall Passage",
  "Whitepeak Ascent",
  "Glacierfall Canyon",
  "Everwinter Gap",
  "Glacierfall Cross",
  "Glacierfall Valley",
  "Whitepeak Spring",
  "Glacierfall Pass",
  "Whitepeak Tundra",
  "Springsump Basin",
  "Springsump Wetland",
  "Springsump Melt",
  "Southgrove Escarp",
  "Southgrove Copse",
  "Southgrove Thicket",
  "Dryvein Cross",
  "Sunstrand Shoal",
  "Sunstrand Delta",
  "Dryvein Plain",
  "Farshore Esker",
  "Dryvein Oasis",
  "Sunstrand Dunes",
  "Farshore Heath",
  "Sunstrand Quicksands",
  "Battlebrae Peaks",
  "Stonelake Fields",
  "Stonelake Hillock",
  "Stonemouth Southbluff",
  "Frostspring Passage",
  "Frostspring Volcano",
  "Whitewall Ridge",
  "Whitewall Pass",
  "Runnelvein Slough",
  "Runnelvein Bog",
  "Runnelvein Sink",
  "Giantweald Copse",
  "Deepwood Gorge",
  "Giantweald Roots",
  "Deepwood Copse",
  "Giantweald Glade",
  "Eye of the Forest",
  "Eldersleep",
  "Skylake Hinterlands",
  "Thunderrock Draw",
  "Floatshoal Floe",
  "Iceburn Firth",
  "Flammog Fork",
  "Iceburn Peaks",
  "Flammog Valley",
  "Iceburn Cliffs",
  "Iceburn Tundra",
  "Flammog Desolation",
  "Glacierfall Fissure",
  "Driprock Tunnel",
  "Shale Underway",
  "Smuggler's Rut",
  "Crosscut Skip",
  "Widemoor Delta",
  "Willowshade Mire",
  "Willowshade Lake",
  "Willowshade Icemarsh",
  "Widemoor Flats",
  "Willowshade Sink",
  "Widemoor Fen",
  "Twinchannel Narrows",
  "Unhallowed Cloister",
  "Westweald Thicket",
  "Driftwood Glen",
  "Westweald Shore",
  "Sandmount Strand",
  "Bleachskull Steppe",
  "Sandmount Esker",
  "Sandrift Steppe",
  "Sandrift Prairie",
  "Sandrift Coast",
  "Sandrift Shore",
  "Farshore Bay",
  "Bleachskull Desert",
  "Sandrift Expanse",
  "Farshore Lagoon",
  "Sandmount Desert",
  "Sandrift Dunes",
  "Farshore Drylands",
  "Sandrift Fringe",
  "Farshore Cape",
  "Sandmount Ascent",
  "Braemore Upland",
  "Windgrass Border",
  "Windgrass Gully",
  "Windgrass Rill",
  "Windgrass Precipice",
  "Braemore Lowland",
  "Windgrass Fields",
  "Windgrass Coast",
  "Highstone Mound",
  "Avalanche Ravine",
  "Frostbite Chasm",
  "Frostseep Ravine",
  "Frostbite Mountain",
  "Frostseep Crevasse",
  "Longfen Marsh",
  "Mudfoot Sump",
  "Mudfoot Mounds",
  "Longfen Veins",
  "Deathreach Priory",
  "Greenhollow Vale",
  "Greenhollow Copse",
  "Highstone Plains",
  "Battlebrae Flatland",
  "Highstone Grassland",
  "Gravemound Brim",
  "Gravemound Hills",
  "Gravemound Slope",
  "Battlebrae Meadow",
  "Windgrass Terrace",
  "Gravemound Knoll",
  "Gravemound Cliffs",
  "Highstone Loch",
  "Redtree Enclave",
  "Deathcap Channel",
  "Glowmire Grotto",
  "Lurkers' Hollow",
  "Middlemurk Path",
  "Craglight Cavern",
  "Deathwisp Sink",
  "Deathwisp Bog",
  "Sunkenbough Woods",
  "Black Monastery",
  "Sunkenbough Spring",
  "Rivercopse Crossing",
  "Driftwood Vale",
  "Hightree Borderlands",
  "Rivercopse Curve",
  "Driftwood Hollow",
  "Rivercopse Path",
  "Darkbough Snag",
  "Rivercopse Fount",
  "Sunfang Ravine",
  "Sunfang Approach",
  "Parchsand Cliffs",
  "Sunfang Cliffs",
  "Sunfang Wasteland",
  "Wailing Bulwark",
  "Sunfang Dawn",
  "Parchsand Drought",
  "Murdergulch Cross",
  "Murdergulch Gap",
  "Razorrock Passage",
  "Razorrock Valley",
  "Highstone Meadow",
  "Battlebrae Plain",
  "Battlebrae Lake",
  "Stonemouth Northbluff",
  "Thunderrock Rapids",
  "Razorrock Ravine",
  "Razorrock Edge",
  "Stonemouth Bay",
  "Thunderrock Ascent",
  "Thunderrock Upland",
  "Murdergulch Trail",
  "Razorrock Chasm",
  "Razorrock Verge",
  "Razorrock Bank",
  "Highstone Plateau",
  "Battlebrae Grassland",
  "Murdergulch Divide",
  "Murdergulch Ravine",
  "Razorrock Gulch",
  "Firesink Caldera",
  "Whitecliff Peak",
  "Firesink Trench",
  "Whitecliff Expanse",
  "Avalanche Incline",
  "Bedrock Passage",
  "Everglow Deep",
  "Longfen Arms",
  "Thirstwater Steppe",
  "Dryvein Riverbed",
  "Thirstwater Waste",
  "Dryvein Steppe",
  "Dryvein End",
  "Thirstwater Gully",
  "Dryvein Confluence",
  "Daemonium Keep",
  "Nightbloom Track",
  "Mudrock Burrow",
  "Deathcreep Adit",
  "Arthur's Rest",
  "Merlyn's Rest",
  "Conquerors' Hall Lvl. 1",
  "Conquerors' Hall Lvl. 2",
  "Conquerors' Hall Lvl. 1",
  "Conquerors' Hall Lvl. 2",
  "Conquerors' Hall Lvl. 1",
  "Conquerors' Hall Lvl. 2",
  "Conquerors' Hall Lvl. 1",
  "Conquerors' Hall Lvl. 2",
  "Conquerors' Hall Lvl. 1",
  "Conquerors' Hall Lvl. 2",
  "Morgana's Rest",
  "Ouyos-Aoeuam",
  "Coues-Exakrom",
  "Puros-Amayam",
  "Pures-Ouozlum",
  "Soros-Axaesum",
  "Huyos-Uxeulum",
  "Ceres-Iooinum",
  "Cetos-Obaelos",
  "Oieos-Umiutum",
  "Sebos-Avoirom",
  "Teros-Auiusum",
  "Oebos-Ixakaum",
  "Touos-Uoemtum",
  "Xasos-Aeoilos",
  "Xuros-Eyoztum",
  "Pasos-Avosam",
  "Oasos-Uromlum",
  "Casos-Uruxtum",
  "Ceros-Aeaylum",
  "Xouos-Aioblos",
  "Oasos-Eraerom",
  "Tetos-Igaelum",
  "Hynos-Oiaelos",
  "Hebos-Ulamsum",
  "Hiros-Iuaerom",
  "Cynos-Avixnum",
  "Conos-Avaelum",
  "Tetos-Ulaurom",
  "Oures-Araosum",
  "Hures-Ugumtum",
  "Hasos-Iuimaum",
  "Foros-Egoisum",
  "Hasos-Agoitum",
  "Setos-Avamsum",
  "Tonos-Obayam",
  "Honos-Umayaum",
  "Huyes-Ogozlum",
  "Curos-Avulsum",
  "Cebos-Avemlum",
  "Hasos-Inayaum",
  "Sasos-Egeylos",
  "Coros-Aiayrom",
  "Hiros-Exozlos",
  "Tiros-Ouultum",
  "Cases-Ugumlos",
  "Fynes-Unavtum",
  "Fetos-Aiaylos",
  "Fouos-Agosaum",
  "Huyos-Eyoztum",
  "Poues-Unatam",
  "Fouos-Amaurom",
  "Suyos-Onaytum",
  "Xasos-Oneulum",
  "Oynos-Oyozam",
  "Coros-Atinaum",
  "Sasos-Oiozlum",
  "Xynos-Oyogam",
  "Cynos-Oxaeaum",
  "Tynos-Atatlos",
  "Firos-Enomaum",
  "Hynes-Exemrom",
  "Hebes-Ouaylos",
  "Foues-Aeaosum",
  "Xilos-Osayam",
  "Casos-Ayosrom",
  "Souos-Ososlos",
  "Xebos-Emimsum",
  "Oetos-Oyexlos",
  "Xebos-Exostum",
  "Tynos-Eyexrom",
  "Casos-Aximam",
  "Hasos-Ayousum",
  "Fasos-Ayiotum",
  "Pebos-Avosrom",
  "Sases-Avuotum",
  "Xases-Oxoulum",
  "Hieos-Avaolum",
  "Xasos-Aoemaum",
  "Hasos-Osuorom",
  "Oynos-Eramtum",
  "Couos-Ayayaum",
  "Siros-Obobrom",
  "Souos-Umogaum",
  "Cilos-Avioaum",
  "Fonos-Aiugsum",
  "Synos-Ayailos",
  "Xiles-Aiavlum",
  "Sases-Aoarsum",
  "Casos-Aiagsum",
  "Tieos-Ayoslum",
  "Hieos-Aiigaum",
  "Poros-Aiayrom",
  "Cilos-Ofailos",
  "Silos-Apenlum",
  "Fynos-Alodrom",
  "Firos-Ezatam",
  "Firos-Osinsum",
  "Soues-Uzurtum",
  "Ooros-Ataltum",
  "Hynes-Ieatun",
  "Fuyes-Izohun",
  "Xetos-Obursum",
  "Oetos-Ofailos",
  "Tynos-Igurlum",
  "Puros-Ofavam",
  "Setos-Aiaitum",
  "Tynos-Uxavrom",
  "Souos-Availos",
  "Sebos-Ugersum",
  "Peros-Aiataum",
  "Pieos-Ofairom",
  "Sieos-Ofugtum",
  "Tasos-Iriglos",
  "Tiros-Odoxlum",
  "Xases-Ataglos",
  "Oires-Oloblum",
  "Firos-Aiavam",
  "Heros-Atoyam",
  "Petos-Aietam",
  "Touos-Ataglos",
  "Poros-Oconun",
  "Honos-Oyezam",
  "Fieos-Atezsum",
  "Ooros-Ecunsum",
  "Coros-Alieam",
  "Couos-Opodam",
  "Horos-Ohenlum",
  "Files-Azazsum",
  "Sasos-Abizaum",
  "Fones-Opavun",
  "Fiees-Ohohtum",
  "Siros-Ofurlos",
  "Oiros-Alaiam",
  "Xiros-Aiairom",
  "Silos-Oyarlum",
  "Fonos-Oleraum",
  "Fieos-Aiuttum",
  "Filos-Abalam",
  "Synos-Oyarlos",
  "Febos-Acalun",
  "Pieos-Eterrom",
  "Feros-Oyuctum",
  "Pynos-Opabrom",
  "Foros-Uzazlum",
  "Cieos-Atatlum",
  "Huros-Atontum",
  "Tonos-Aboysum",
  "Hiles-Izizaum",
  "Sebos-Oyohun",
  "Cilos-Otatrom",
  "Oasitos-Aoeuam",
  "Curites-Exakrom",
  "Petitos-Amayam",
  "Pynites-Ouozlum",
  "Suyitos-Axaesum",
  "Honitos-Uxeulum",
  "Cuyites-Iooinum",
  "Cieitos-Obaelos",
  "Oonitos-Umiutum",
  "Siritos-Avoirom",
  "Tuyitos-Auiusum",
  "Oieitos-Ixakaum",
  "Turitos-Uoemtum",
  "Xouitos-Aeoilos",
  "Xouitos-Eyoztum",
  "Peritos-Avosam",
  "Oynitos-Uromlum",
  "Conitos-Uruxtum",
  "Cebitos-Aeaylum",
  "Xuyitos-Aioblos",
  "Oebitos-Eraerom",
  "Tebitos-Igaelum",
  "Huritos-Oiaelos",
  "Hynitos-Ulamsum",
  "Hetitos-Iuaerom",
  "Cetitos-Avixnum",
  "Casitos-Avaelum",
  "Tasitos-Ulaurom",
  "Oynites-Araosum",
  "Hilites-Ugumtum",
  "Huritos-Iuimaum",
  "Fynitos-Egoisum",
  "Huyitos-Agoitum",
  "Soritos-Avamsum",
  "Tasitos-Obayam",
  "Hasitos-Umayaum",
  "Hynites-Ogozlum",
  "Ceritos-Avulsum",
  "Coritos-Avemlum",
  "Heritos-Inayaum",
  "Seritos-Egeylos",
  "Cetitos-Aiayrom",
  "Heritos-Exozlos",
  "Tieitos-Ouultum",
  "Cieites-Ugumlos",
  "Fieites-Unavtum",
  "Foritos-Aiaylos",
  "Fynitos-Agosaum",
  "Heritos-Eyoztum",
  "Pirites-Unatam",
  "Fonitos-Amaurom",
  "Seritos-Onaytum",
  "Xetitos-Oneulum",
  "Oebitos-Oyozam",
  "Casitos-Atinaum",
  "Souitos-Oiozlum",
  "Xebitos-Oyogam",
  "Conitos-Oxaeaum",
  "Turitos-Atatlos",
  "Feritos-Enomaum",
  "Hebites-Exemrom",
  "Hurites-Ouaylos",
  "Fynites-Aeaosum",
  "Xoritos-Osayam",
  "Cieitos-Ayosrom",
  "Synitos-Ososlos",
  "Xetitos-Emimsum",
  "Oeritos-Oyexlos",
  "Xoritos-Exostum",
  "Tieitos-Eyexrom",
  "Cetitos-Aximam",
  "Hynitos-Ayousum",
  "Fuyitos-Ayiotum",
  "Petitos-Avosrom",
  "Suyites-Avuotum",
  "Xerites-Oxoulum",
  "Hasitos-Avaolum",
  "Xilitos-Aoemaum",
  "Hilitos-Osuorom",
  "Oiritos-Eramtum",
  "Curitos-Ayayaum",
  "Setitos-Obobrom",
  "Sasitos-Umogaum",
  "Cieitos-Avioaum",
  "Fynitos-Aiugsum",
  "Sonitos-Ayailos",
  "Xonites-Aiavlum",
  "Synites-Aoarsum",
  "Cynitos-Aiagsum",
  "Tetitos-Ayoslum",
  "Hilitos-Aiigaum",
  "Ponitos-Aiayrom",
  "Conitos-Ofailos",
  "Soritos-Apenlum",
  "Firitos-Alodrom",
  "Fynitos-Ezatam",
  "Feritos-Osinsum",
  "Suyites-Uzurtum",
  "Ouritos-Ataltum",
  "Hurites-Ieatun",
  "Filites-Izohun",
  "Xynitos-Obursum",
  "Ouritos-Ofailos",
  "Tonitos-Igurlum",
  "Piritos-Ofavam",
  "Soritos-Aiaitum",
  "Tonitos-Uxavrom",
  "Synitos-Availos",
  "Sasitos-Ugersum",
  "Puyitos-Aiataum",
  "Pouitos-Ofairom",
  "Suyitos-Ofugtum",
  "Toritos-Iriglos",
  "Tebitos-Odoxlum",
  "Xurites-Ataglos",
  "Oynites-Oloblum",
  "Furitos-Aiavam",
  "Hynitos-Atoyam",
  "Pynitos-Aietam",
  "Tilitos-Ataglos",
  "Peritos-Oconun",
  "Hynitos-Oyezam",
  "Fasitos-Atezsum",
  "Oeritos-Ecunsum",
  "Casitos-Alieam",
  "Cilitos-Opodam",
  "Huyitos-Ohenlum",
  "Fasites-Azazsum",
  "Silitos-Abizaum",
  "Febites-Opavun",
  "Ferites-Ohohtum",
  "Synitos-Ofurlos",
  "Oouitos-Alaiam",
  "Xoritos-Aiairom",
  "Sasitos-Oyarlum",
  "Fasitos-Oleraum",
  "Fouitos-Aiuttum",
  "Fynitos-Abalam",
  "Suyitos-Oyarlos",
  "Fuyitos-Acalun",
  "Pilitos-Eterrom",
  "Fasitos-Oyuctum",
  "Piritos-Opabrom",
  "Filitos-Uzazlum",
  "Cynitos-Atatlum",
  "Hebitos-Atontum",
  "Tuyitos-Aboysum",
  "Honites-Izizaum",
  "Siritos-Oyohun",
  "Cieitos-Otatrom",
  "Corrupted Lair",
  "Corrupted Lair",
  "Corrupted Lair",
  "PSG-0038",
  "PSG-0039",
  "PSG-0042",
  "PSG-0044",
  "PSG-0045",
  "PSG-0048",
  "PSG-0049",
  "PSG-0050",
  "PSG-0051",
  "PSG-0052",
  "PSG-0053",
  "PSG-0054",
  "Corrupted Lair",
  "Corrupted Lair",
  "Corrupted Lair",
  "Corrupted Lair",
  "PSG-0008",
  "PSG-0009",
  "PSG-0010",
  "PSG-0011",
  "PSG-0012",
  "PSG-0013",
  "PSG-0014",
  "PSG-0015",
  "PSG-0016",
  "PSG-0017",
  "PSG-0018",
  "PSG-0019",
  "PSG-0020",
  "PSG-0021",
  "PSG-0022",
  "PSG-0023",
  "PSG-0024",
  "PSG-0025",
  "PSG-0026",
  "PSG-0027",
  "PSG-0028",
  "PSG-0029",
  "PSG-0030",
  "PSG-0031",
  "PSG-0032",
  "PSG-0033",
  "PSG-0034",
  "PSG-0035",
  "PSG-0036",
  "PSG-0037",
  "PSG-0040",
  "PSG-0041",
  "PSG-0043",
  "PSG-0046",
  "PSG-0047",
  "Quaent-Vynsum",
  "Quaent-Al-Vynsum",
  "Quaent-Tersis",
  "Quaent-Al-Tersis",
  "Quaent-Viesom",
  "Quaent-Al-Viesom",
  "Quatun-Nusas",
  "Quatun-Et-Nusas",
  "Quaent-Qintis",
  "Quaent-Al-Qintis",
  "Quatun-Odetum",
  "Quatun-Et-Odetum",
  "Quaent-Al-Odesum",
  "Quaent-In-Odesum",
  "Quaent-Al-Nusis",
  "Quaent-In-Nusis",
  "Qiient-Tersom",
  "Qiient-In-Tersom",
  "Qiient-Odesas",
  "Qiient-Qi-Odesas",
  "Qiient-Nutis",
  "Qiient-In-Nutis",
  "Qiient-Vyntum",
  "Qiient-In-Vyntum",
  "Qiient-Al-Odesum",
  "Qiient-Si-Odesum",
  "Qiient-Al-Vynsis",
  "Qiient-Qi-Vynsis",
  "Qiitun-Et-Vynsom",
  "Qiitun-Si-Vynsom",
  "Qiient-Al-Tersas",
  "Qiient-Qi-Tersas",
  "Qiitun-Vietis",
  "Qiitun-Et-Vietis",
  "Qiient-Et-Tertum",
  "Qiient-Si-Tertum",
  "Qiient-Qinsum",
  "Qiient-Et-Qinsum",
  "Qiient-Al-Viesis",
  "Qiient-In-Viesis",
  "Qiient-Al-Nusom",
  "Qiient-Qi-Nusom",
  "Qiient-Et-Nusas",
  "Qiient-Si-Nusas",
  "Qiient-Et-Odetis",
  "Qiient-Sa-Odetis",
  "Qiient-In-Odetum",
  "Qiient-Oc-Odetum",
  "Qiitun-Duosum",
  "Qiitun-Al-Duosum",
  "Qiient-Al-Qinsis",
  "Qiient-In-Qinsis",
  "Secent-Odesom",
  "Secent-Qi-Odesom",
  "Sectun-Tersas",
  "Sectun-Et-Tersas",
  "Secent-Al-Odetis",
  "Secent-Si-Odetis",
  "Secent-Vyntum",
  "Secent-Et-Vyntum",
  "Secent-Viesum",
  "Secent-Al-Viesum",
  "Secent-Et-Odesis",
  "Secent-Sa-Odesis",
  "Sectun-Qinsom",
  "Sectun-In-Qinsom",
  "Secent-Al-Qinsom",
  "Secent-Qi-Qinsom",
  "Sectun-Al-Vyntis",
  "Sectun-In-Vyntis",
  "Secent-Nutum",
  "Secent-Al-Nutum",
  "Secent-Al-Tersum",
  "Secent-In-Tersum",
  "Sectun-In-Odesis",
  "Sectun-Oc-Odesis",
  "Secent-Duosom",
  "Secent-Al-Duosom",
  "Secent-Et-Qinsas",
  "Secent-Si-Qinsas",
  "Setent-Vietis",
  "Setent-Al-Vietis",
  "Settun-Odetum",
  "Settun-Et-Odetum",
  "Setent-Nusum",
  "Setent-Et-Nusum",
  "Settun-Vynsis",
  "Settun-Al-Vynsis",
  "Settun-Tersom",
  "Settun-Al-Tersom",
  "Setent-Duosas",
  "Setent-Al-Duosas",
  "Setent-Qintis",
  "Setent-Et-Qintis",
  "Settun-Al-Odetum",
  "Settun-In-Odetum",
  "Setent-Al-Qinsum",
  "Setent-In-Qinsum",
  "Settun-Al-Nusis",
  "Settun-In-Nusis",
  "Corrupted Lair",
  "Corrupted Lair",
  "Corrupted Lair",
  "Corrupted Lair",
  "Corrupted Lair",
  "Corrupted Lair",
  "Corrupted Lair",
  "Corrupted Lair",
  "Corrupted Lair",
  "Corrupted Lair",
  "Corrupted Lair",
  "Corrupted Lair",
  "Corrupted Lair",
  "CrystalRealmDebug",
  "Conquerors' Hall Lvl. 3",
  "Conquerors' Hall Lvl. 3",
  "Conquerors' Hall Lvl. 3",
  "Conquerors' Hall Lvl. 3",
  "Conquerors' Hall Lvl. 3",
  "Champions' Realm",
  "VegAnimTest",
  "Large Crystal Realm",
  "The Plains",
  "The Plains",
  "The Plains",
  "The Hill",
  "The Hill",
  "The Hill",
  "The Boneyard",
  "The Boneyard",
  "The Boneyard",
  "The Four Bridges",
  "The Four Bridges",
  "The Four Bridges",
  "The Traverse",
  "The Traverse",
  "The Traverse",
  "The Fortress",
  "The Fortress",
  "The Fortress",
  "The Pit",
  "The Pit",
  "The Pit",
  "The Courtyard",
  "The Courtyard",
  "The Courtyard",
  "The Tribunal",
  "The Tribunal",
  "The Tribunal",
  "The Citadel",
  "The Citadel",
  "The Citadel",
  "Murky Fen",
  "Fog Fen",
  "Drownhorse Basin",
  "Slithertail Marsh",
  "Wanderlure Basin",
  "Falsestep Marsh",
  "Darkground Swamp",
  "Anklesnag Mire",
  "Dusktree Swamp",
  "Flynsdell",
  "Pinecopse",
  "Deeproot Wood",
  "Aspenwood",
  "Spindlewood",
  "Owlsong Glen",
  "Nightbloom Forest",
  "Dryfield Meadow",
  "Sandgust Cleft",
  "Longshadow Plain",
  "Flatriver Trough",
  "Redstone Plain",
  "Flimmerair Steppe",
  "Goldshimmer Plain",
  "Kilmar Tor",
  "Carns Hill",
  "Brons Hill",
  "Felniks Hill",
  "Adrens Hill",
  "Garrow Fell",
  "Broken Fell",
  "Pen Fenair",
  "Cairn Drain",
  "Caulder Fissure",
  "Cairn Cloch",
  "Creag Dhor",
  "Creag Meagir",
  "Domhain Chasm",
  "Creag's Way",
  "Chasmlight Cave",
  "PSG-H-0001",
  "Boulder Deep",
  "PSG-H-0002",
  "Drystone Channel",
  "PSG-0001",
  "PSG-0002",
  "The Plains",
  "The Plains",
  "The Plains",
  "The Hill",
  "The Hill",
  "The Hill",
  "The Boneyard",
  "The Boneyard",
  "The Boneyard",
  "The Four Bridges",
  "The Four Bridges",
  "The Four Bridges",
  "The Traverse",
  "The Traverse",
  "The Traverse",
  "The Fortress",
  "The Fortress",
  "The Fortress",
  "The Pit",
  "The Pit",
  "The Pit",
  "The Courtyard",
  "The Courtyard",
  "The Courtyard",
  "The Tribunal",
  "The Tribunal",
  "The Tribunal",
  "The Citadel",
  "The Citadel",
  "The Citadel",
  "Stoneroot Caverns",
  "Stoneroot Caverns",
  "Stoneroot Caverns",
  "Stoneroot Caverns",
  "Stoneroot Caverns",
  "Stoneroot Caverns",
  "Stoneroot Caverns",
  "Stoneroot Caverns",
  "Stoneroot Caverns",
  "Stoneroot Caverns",
  "Stoneroot Caverns",
  "Stoneroot Caverns",
  "Stoneroot Caverns",
  "Stoneroot Caverns",
  "Stoneroot Caverns",
  "Stoneroot Caverns",
  "Stoneroot Caverns",
  "Stoneroot Caverns",
  "Stoneroot Caverns",
  "Stoneroot Caverns",
  "Stoneroot Caverns",
  "Cathedral of Light",
  "Cathedral of Light",
  "Cathedral of Light",
  "Cathedral of Light",
  "Cathedral of Light",
  "Cathedral of Light",
  "Cathedral of Light",
  "Cathedral of Light",
  "Cathedral of Light",
  "Cathedral of Light",
  "Cathedral of Light",
  "Cathedral of Light",
  "Cathedral of Light",
  "Cathedral of Light",
  "Cathedral of Light",
  "Cathedral of Light",
  "Cathedral of Light",
  "Cathedral of Light",
  "Cathedral of Light",
  "Cathedral of Light",
  "Cathedral of Light",
  "Cathedral of Light",
  "Cathedral of Light",
  "Cathedral of Light",
  "Cathedral of Light",
  "Chambers of Truth",
  "Chambers of Truth",
  "Chambers of Truth",
  "Chambers of Truth",
  "Chambers of Truth",
  "Chambers of Truth",
  "Chambers of Truth",
  "Chambers of Truth",
  "Chambers of Truth",
  "Chambers of Truth",
  "Chambers of Truth",
  "Chambers of Truth",
  "Chambers of Truth",
  "Chambers of Truth",
  "Chambers of Truth",
  "Chambers of Truth",
  "Chambers of Truth",
  "Chambers of Truth",
  "Chambers of Truth",
  "Chambers of Truth",
  "Chambers of Truth",
  "Chambers of Truth",
  "Chambers of Truth",
  "Chambers of Truth",
  "Chambers of Truth",
  "Hallowed Crypt",
  "Hallowed Crypt",
  "Hallowed Crypt",
  "Hallowed Crypt",
  "Hallowed Crypt",
  "Hallowed Crypt",
  "Hallowed Crypt",
  "Hallowed Crypt",
  "Exalted Crypt",
  "Exalted Crypt",
  "Exalted Crypt",
  "Exalted Crypt",
  "Exalted Crypt",
  "Exalted Crypt",
  "Exalted Crypt",
  "Exalted Crypt",
  "Exalted Crypt",
  "Exalted Crypt",
  "Exalted Crypt",
  "Exalted Crypt",
  "Exalted Crypt",
  "Exalted Crypt",
  "Exalted Crypt",
  "Exalted Crypt",
  "Exalted Crypt",
  "Exalted Crypt",
  "Exalted Crypt",
  "Exalted Crypt",
  "Exalted Crypt",
  "Exalted Crypt",
  "Exalted Crypt",
  "Exalted Crypt",
  "Exalted Crypt",
  "Hallowed Undercrypt",
  "Hallowed Undercrypt",
  "Hallowed Undercrypt",
  "Hallowed Undercrypt",
  "Hallowed Undercrypt",
  "Hallowed Undercrypt",
  "Hallowed Undercrypt",
  "Hallowed Undercrypt",
  "Exalted Undercrypt",
  "Exalted Undercrypt",
  "Exalted Undercrypt",
  "Exalted Undercrypt",
  "Exalted Undercrypt",
  "Exalted Undercrypt",
  "Exalted Undercrypt",
  "Exalted Undercrypt",
  "Exalted Undercrypt",
  "Exalted Undercrypt",
  "Exalted Undercrypt",
  "Exalted Undercrypt",
  "Exalted Undercrypt",
  "Exalted Undercrypt",
  "Exalted Undercrypt",
  "Exalted Undercrypt",
  "Exalted Undercrypt",
  "Exalted Undercrypt",
  "Exalted Undercrypt",
  "Exalted Undercrypt",
  "Exalted Undercrypt",
  "Exalted Undercrypt",
  "Exalted Undercrypt",
  "Exalted Undercrypt",
  "Exalted Undercrypt",
  "Deepwood Enclave",
  "Deepwood Enclave",
  "Deepwood Enclave",
  "Stoneroot Caverns",
  "Trinity Hall",
  "Trinity Hall",
  "Trinity Hall",
  "Trinity Hall",
  "Conquerors' Hall Lvl. 4",
  "Conquerors' Hall Lvl. 4",
  "Conquerors' Hall Lvl. 4",
  "Conquerors' Hall Lvl. 4",
  "Conquerors' Hall Lvl. 4",
  "DNG-UND-01-MAIN-06",
  "DNG-UND-01-SUB-06",
  "Stoneroot Caverns",
  "Exalted Crypt",
  "Exalted Undercrypt",
  "LEGACY-KEEPER-01",
  "LEGACY-KEEPER-SOLO-01",
  "LEGACY-UNDEAD-01",
  "LEGACY-UNDEAD-02",
  "Heretic Cellar Network",
  "Thetford Portal",
  "Lymhurst Portal",
  "Bridgewatch Portal",
  "Martlock Portal",
  "Fort Sterling Portal",
  "0302",
  "0303",
  "0304",
  "1302",
  "1303",
  "1304",
  "2302",
  "2303",
  "2304",
  "3302",
  "3303",
  "3304",
  "4302",
  "4303",
  "4304",
  "Crystal Realm",
  "Crystal Realm",
  "Heretic Cellar Network",
  "Heretic Cellar Network",
  "Heretic Cellar Network",
  "Heretic Cellar Network",
  "Crystal Realm",
  "Crystal Realm",
  "Brecilien",
  "Brecilien",
  "Brecilien Bank",
  "Brecilien Market",
  "ISLAND-PLAYER-MISTS-0001f",
  "Brecilien Weald",
  "Brecilien Copse",
  "Brecilien Grove",
  "Brecilien Thicket",
  "ISLAND-PLAYER-MISTS-0001a",
  "ISLAND-PLAYER-MISTS-0001b",
  "ISLAND-PLAYER-MISTS-0001c",
  "ISLAND-PLAYER-MISTS-0001d",
  "ISLAND-PLAYER-MISTS-0001e",
  "Mists Dungeon",
  "Conquerors' Hall Lvl. 5",
  "Conquerors' Hall Lvl. 5",
  "Conquerors' Hall Lvl. 5",
  "Conquerors' Hall Lvl. 5",
  "Conquerors' Hall Lvl. 5",
  "3010",
  "3012-HALL-02",
  "ISLAND-PLAYER-FOREST-0001a",
  "ISLAND-PLAYER-FOREST-0001b",
  "ISLAND-PLAYER-FOREST-0001c",
  "ISLAND-PLAYER-FOREST-0001d",
  "ISLAND-PLAYER-FOREST-0001e",
  "ISLAND-PLAYER-FOREST-0001f",
  "ISLAND-PLAYER-HIGHLAND-0001a",
  "ISLAND-PLAYER-HIGHLAND-0001b",
  "ISLAND-PLAYER-HIGHLAND-0001c",
  "ISLAND-PLAYER-HIGHLAND-0001d",
  "ISLAND-PLAYER-HIGHLAND-0001e",
  "ISLAND-PLAYER-HIGHLAND-0001f",
  "ISLAND-PLAYER-MOUNTAIN-0001a",
  "ISLAND-PLAYER-MOUNTAIN-0001b",
  "ISLAND-PLAYER-MOUNTAIN-0001c",
  "ISLAND-PLAYER-MOUNTAIN-0001d",
  "ISLAND-PLAYER-MOUNTAIN-0001e",
  "ISLAND-PLAYER-MOUNTAIN-0001f",
  "ISLAND-PLAYER-CAERLEON-0001a",
  "ISLAND-PLAYER-CAERLEON-0001b",
  "ISLAND-PLAYER-CAERLEON-0001c",
  "ISLAND-PLAYER-CAERLEON-0001d",
  "ISLAND-PLAYER-CAERLEON-0001e",
  "ISLAND-PLAYER-CAERLEON-0001f",
  "ISLAND-PLAYER-STEPPE-0001a",
  "ISLAND-PLAYER-STEPPE-0001b",
  "ISLAND-PLAYER-STEPPE-0001c",
  "ISLAND-PLAYER-STEPPE-0001d",
  "ISLAND-PLAYER-STEPPE-0001e",
  "ISLAND-PLAYER-STEPPE-0001f",
  "ISLAND-PLAYER-SWAMP-0001a",
  "ISLAND-PLAYER-SWAMP-0001b",
  "ISLAND-PLAYER-SWAMP-0001c",
  "ISLAND-PLAYER-SWAMP-0001d",
  "ISLAND-PLAYER-SWAMP-0001e",
  "ISLAND-PLAYER-SWAMP-0001f",
] as const;

export type WorldName = (typeof worldNames)[number];

export const worldMeta = {
  "1302": { index: "1302" },
  "1303": { index: "1303" },
  "1304": { index: "1304" },
  "2302": { index: "2302" },
  "2303": { index: "2303" },
  "2304": { index: "2304" },
  "3010": { index: "3010" },
  "3302": { index: "3302" },
  "3303": { index: "3303" },
  "3304": { index: "3304" },
  "4302": { index: "4302" },
  "4303": { index: "4303" },
  "4304": { index: "4304" },
  Debug: { index: "Debug" },
  "ISLAND-GUILD-0001a_ISL_DL_T1_NON": { index: "ISLAND-GUILD-0001a" },
  "ISLAND-PLAYER-0001a_ISL_DL_T1_NON": { index: "ISLAND-PLAYER-0001a" },
  "ISLAND-PLAYER-0001f_ISL_DL_T1_NON": { index: "ISLAND-PLAYER-0001f" },
  "ISLAND-PLAYER-0001e_ISL_DL_T1_NON": { index: "ISLAND-PLAYER-0001e" },
  "ISLAND-PLAYER-0001d_ISL_DL_T1_NON": { index: "ISLAND-PLAYER-0001d" },
  "ISLAND-PLAYER-0001c_ISL_DL_T1_NON": { index: "ISLAND-PLAYER-0001c" },
  "ISLAND-PLAYER-0001b_ISL_DL_T1_NON": { index: "ISLAND-PLAYER-0001b" },
  "ISLAND-GUILD-0001b_ISL_DL_T1_NON": { index: "ISLAND-GUILD-0001b" },
  "ISLAND-GUILD-0001c_ISL_DL_T1_NON": { index: "ISLAND-GUILD-0001c" },
  "ISLAND-GUILD-0001d_ISL_DL_T1_NON": { index: "ISLAND-GUILD-0001d" },
  "ISLAND-GUILD-0001e_ISL_DL_T1_NON": { index: "ISLAND-GUILD-0001e" },
  "ISLAND-GUILD-0001f_ISL_DL_T1_NON": { index: "ISLAND-GUILD-0001f" },
  "Swamp Cross": { index: "0004" },
  "Tharcal Fissure": { index: "4206" },
  "Mushroom Cave": { index: "MushroomCave-HRD" },
  "Fishy Business": { index: "FishyBusiness-HRD" },
  "Stone Wars": { index: "StoneWars-HRD" },
  "Cairn Darg": { index: "4209" },
  "Gwan Gorge": { index: "4210" },
  "Malag Crevasse": { index: "4215" },
  "Creag Morr": { index: "4216" },
  "Cairn Camain": { index: "4213" },
  "Cairn Glascore": { index: "4212" },
  "Pen Gent": { index: "4207" },
  "Pen Garn": { index: "4201" },
  "Crose Gorge": { index: "4203" },
  "Birken Fell": { index: "3201" },
  "Eldon Hill": { index: "3204" },
  "Lewsdon Hill": { index: "3203" },
  "Blackthorn Quarry": { index: "3207" },
  Haytor: { index: "3206" },
  "Brent Knoll": { index: "3209" },
  "Mase Knoll": { index: "3210" },
  "Croker Hill": { index: "3212" },
  "Goffers Knoll": { index: "3215" },
  "Vixen Tor": { index: "3213" },
  "Prospector's Hope": { index: "2215" },
  "Steelhide Meadow": { index: "2213" },
  "Longmarch Meadow": { index: "2212" },
  "Lazygrass Plain": { index: "2209" },
  "Snapshaft Trough": { index: "2210" },
  "Drywater Meadow": { index: "2207" },
  "Parchthroat Plain": { index: "2206" },
  "Deadvein Gully": { index: "2204" },
  "Roastcorpse Steppe": { index: "2203" },
  "Kindlegrass Steppe": { index: "2201" },
  Ferndell: { index: "1215" },
  "Wyre Forest": { index: "1213" },
  Stagbourne: { index: "1212" },
  Murkweald: { index: "1210" },
  "Longtimber Glen": { index: "1209" },
  Birchcopse: { index: "1207" },
  "Willow Wood": { index: "1206" },
  Oakcopse: { index: "1204" },
  Rowanwood: { index: "1203" },
  Larchroad: { index: "1201" },
  "Pen Kerrig": { index: "4204" },
  Slimehag: { index: "0214" },
  "Bonepool Marsh": { index: "0212" },
  "Spectral Sump": { index: "0211" },
  "Willowsigh Marsh": { index: "0203" },
  "Stumprot Swamp": { index: "0208" },
  "Dusklight Fen": { index: "0206" },
  "Dewleaf Fen": { index: "0209" },
  Stinkhag: { index: "0205" },
  Chillhag: { index: "0202" },
  "Slowtree Plain": { index: "2208" },
  "Smoothfloor Cleft": { index: "2211" },
  "Gutras Hill": { index: "3205" },
  Mardale: { index: "3202" },
  "Wispwhisper Marsh": { index: "0210" },
  "Curlew Fen": { index: "0213" },
  "Saddle Tor": { index: "3211" },
  "Windripple Fen": { index: "0204" },
  "Mawar Gorge": { index: "4208" },
  Russerdell: { index: "1202" },
  "Bryn Gorge": { index: "4202" },
  "Cairn Gorm": { index: "4205" },
  "Lumber Lunacy": { index: "LumberCamp-HRD" },
  "Preaching to the Dead": { index: "RecruitmentOfTheDead-HRD" },
  "Bowscale Fell": { index: "3208" },
  "Cairn Fidair": { index: "4214" },
  "Creag Garr": { index: "4211" },
  "Nightcreak Marsh": { index: "0207" },
  "Fractured Ground": { index: "2214" },
  "Cracked Earth": { index: "2202" },
  Redlake: { index: "1208" },
  "Yew Wood": { index: "1211" },
  "Highbole Glen": { index: "1205" },
  "Hornbeam Wood": { index: "1214" },
  "Steppe Cross": { index: "2002" },
  "Highland Cross": { index: "3002" },
  "Haldon Tor": { index: "3214" },
  Martlock: { index: "3004" },
  "Fort Sterling": { index: "4000" },
  "Forest Cross": { index: "1006" },
  "Mountain Cross": { index: "4006" },
  Thetford: { index: "0000" },
  "Sleetwater Basin": { index: "0201" },
  Lymhurst: { index: "1000" },
  Camlann: { index: "0005" },
  Astolat: { index: "2009" },
  "Curious Excavation": { index: "Mine-SOLO" },
  "Lurking Underneath": { index: "SewersMaintenance-HRD" },
  Bridgewatch: { index: "2000" },
  "Rock Adit": { index: "PSG-0003" },
  "Sabertooth Den": { index: "PSG-0004" },
  "Swamp Burrow": { index: "PSG-0005" },
  "Ore Adit": { index: "PSG-0006" },
  "Forest Burrow": { index: "PSG-0007" },
  "The Underway": { index: "CenterCity-DNG-01" },
  Caerleon: { index: "3003" },
  "Runnel Sink": { index: "3245" },
  "Inis Mon": { index: "1007" },
  "Three Sisters": { index: "ThreeSisters-HRD" },
  "A Fistful of Silver": { index: "FistfulOfSilver-GROUP" },
  Cedarcopse: { index: "1246" },
  "Bellever Tor": { index: "3249" },
  "Pen Uchaf": { index: "4249" },
  "Shiftshadow Expanse": { index: "2205" },
  "Caerleon Market": { index: "3013-Auction2" },
  "Bank of Caerleon": { index: "3006" },
  "Eternal Battle": { index: "EternalBattle-HRD" },
  Arena1: { index: "ARENA-01" },
  Arena2: { index: "ARENA-01#1" },
  "The Arena": { index: "ARENA-STANDARD" },
  "Bank of Thetford": { index: "0006" },
  "Thetford Market": { index: "0007" },
  "Bank of Lymhurst": { index: "1001" },
  "Lymhurst Market": { index: "1002" },
  "Bank of Bridgewatch": { index: "2003" },
  "Bridgewatch Market": { index: "2004" },
  "Bank of Martlock": { index: "3007" },
  "Martlock Market": { index: "3008" },
  "Bank of Fort Sterling": { index: "4001" },
  "Fort Sterling Market": { index: "4002" },
  "A Fistful Of Silver": { index: "FistfulOfSilver-HRD" },
  "In the Raven's Claws": { index: "Torturer-HRD" },
  "Farmland Skirmish": { index: "ARENA-FarmLand" },
  "HomeTerritory Skirmish": { index: "ARENA-HomeTerritory" },
  "Resource Skirmish": { index: "ARENA-Resources1" },
  "Resource Skirmish 2": { index: "ARENA-Resources2" },
  "Crystal Realm": { index: "CrystalRealm02-Nonlethal" },
  "The Lighthouse": { index: "1008" },
  "Forgotten Woods": { index: "1009" },
  "Mountain Fort": { index: "1010" },
  "The Cove": { index: "1011" },
  "ARENA-City": { index: "ARENA-City" },
  HIDEOUT: { index: "HIDEOUT-0001c" },
  "Northstrand Dunes": { index: "2305" },
  "Northstrand Beach": { index: "2326" },
  "Scuttlesink Mouth": { index: "0324" },
  "Deepwood Dell": { index: "1306" },
  "Whitebank Stream": { index: "4308" },
  "Whitebank Shore": { index: "4309" },
  "Whitebank Cross": { index: "4311" },
  "Whitebank Wall": { index: "4326" },
  "Meltwater Bog": { index: "0307" },
  "Whitebank Descent": { index: "4305" },
  "Whitebank Ridge": { index: "4338" },
  "Timberslope Dell": { index: "1326" },
  "Deepwood Pines": { index: "1340" },
  "Frostpeak Vista": { index: "4306" },
  "Frostpeak Ascent": { index: "4324" },
  "Floatshoal Fissure": { index: "4327" },
  "Floatshoal Bight": { index: "4339" },
  "Darkseep Core": { index: "PSG-0039#2" },
  "Meltwater Delta": { index: "0325" },
  "Meltwater Sump": { index: "0338" },
  "Skysand Plateau": { index: "2307" },
  "Everwinter Crossing": { index: "4307" },
  "Everwinter Plain": { index: "4323" },
  "Everwinter Gorge": { index: "4325" },
  "Scuttlesink Marsh": { index: "0353" },
  "Brambleshore Hinterlands": { index: "1305" },
  "Shaleheath Steep": { index: "3338" },
  "Everwinter Reach": { index: "4321" },
  "Everwinter Peak": { index: "4322" },
  "Everwinter Passage": { index: "4337" },
  "Everwinter Expanse": { index: "4340" },
  "Everwinter Incline": { index: "4353" },
  "Stoneslip Passage": { index: "PSG-0042#1" },
  "Whitecap Cave": { index: "PSG-0049#1" },
  "Scuttlesink Pools": { index: "0306" },
  "Timbertop Dale": { index: "1325" },
  "Timbertop Wood": { index: "1338" },
  "Timbertop Escarp": { index: "1353" },
  "Shaleheath Hills": { index: "3326" },
  "Everwinter Shores": { index: "4310" },
  "Wetgrave Bog": { index: "0305" },
  "Wetgrave Swale": { index: "0339" },
  "Wetgrave Marsh": { index: "0342" },
  "Timberslope Grove": { index: "1339" },
  "Timberslope Bridge": { index: "1354" },
  "Swiftsands Plain": { index: "2306" },
  "Drybasin Riverbed": { index: "2308" },
  "Swiftsands Basin": { index: "2339" },
  "Swiftsands Chaparral": { index: "2354" },
  "Skylake Bridge": { index: "3327" },
  "Greenshore Bay": { index: "1355" },
  "Flatrock Cliffs": { index: "3305" },
  "Skullmarsh Lower": { index: "0315" },
  "Skullmarsh Upper": { index: "0343" },
  "Greenshore Peninsula": { index: "1307" },
  "Giantweald Dale": { index: "1308" },
  "Watchwood Precipice": { index: "1311" },
  "Watchwood Grove": { index: "1315" },
  "Giantweald Woods": { index: "1328" },
  "Watchwood Lakeside": { index: "1329" },
  "Watchwood Bluffs": { index: "1330" },
  "Giantweald Edge": { index: "1341" },
  "Slakesands Canyon": { index: "2309" },
  "Drybasin Oasis": { index: "2341" },
  "Slakesands Mesa": { index: "2342" },
  "Flatrock Plateau": { index: "3328" },
  "Munten Rise": { index: "4315" },
  "Munten Tundra": { index: "4331" },
  "Munten Fell": { index: "4345" },
  "Hightree Steep": { index: "1313" },
  "Hightree Lake": { index: "1316" },
  "Hightree Dale": { index: "1317" },
  "Hightree Strand": { index: "1319" },
  "Hightree Glade": { index: "1320" },
  "Hightree Enclave": { index: "1322" },
  "Hightree Pass": { index: "1332" },
  "Hightree Levee": { index: "1335" },
  "Hightree Cliffs": { index: "1336" },
  "Hightree Isle": { index: "1345" },
  "Hightree Hillock": { index: "1347" },
  "Glacierbreak Summit": { index: "4332" },
  "Drownfield Course": { index: "0308" },
  "Widemoor Shore": { index: "0309" },
  "Widemoor Pool": { index: "0312" },
  "Willowshade Wetlands": { index: "0314" },
  "Widemoor Estuary": { index: "0316" },
  "Widemoor Hills": { index: "0327" },
  "Drownfield Wetland": { index: "0328" },
  "Widemoor End": { index: "0330" },
  "Willowshade Pools": { index: "0331" },
  "Widemoor Woods": { index: "0333" },
  "Willowshade Hills": { index: "0344" },
  "Timberscar Dell": { index: "1309" },
  "Timberscar Copse": { index: "1342" },
  "Drytop Riverbed": { index: "2327" },
  "Drytop Pillars": { index: "2328" },
  "Stalagmite Adit": { index: "PSG-0044#1" },
  "Drownfield Mire": { index: "0310" },
  "Drownfield Fen": { index: "0313" },
  "Drownfield Slough": { index: "0329" },
  "Drownfield Rut": { index: "0332" },
  "Drownfield Quag": { index: "0340" },
  "Meltwater Channel": { index: "0354" },
  "Drownfield Sink": { index: "0355" },
  "Deadpine Forest": { index: "1312" },
  "Skysand Ridge": { index: "2340" },
  "Citadel of Ash": { index: "2355" },
  "Glacierfall Passage": { index: "4312" },
  "Whitepeak Ascent": { index: "4317" },
  "Glacierfall Canyon": { index: "4329" },
  "Everwinter Gap": { index: "4341" },
  "Glacierfall Cross": { index: "4343" },
  "Glacierfall Valley": { index: "4344" },
  "Whitepeak Spring": { index: "4348" },
  "Glacierfall Pass": { index: "4355" },
  "Whitepeak Tundra": { index: "4357" },
  "Springsump Basin": { index: "0321" },
  "Springsump Wetland": { index: "0335" },
  "Springsump Melt": { index: "0351" },
  "Southgrove Escarp": { index: "1314" },
  "Southgrove Copse": { index: "1337" },
  "Southgrove Thicket": { index: "1350" },
  "Dryvein Cross": { index: "2315" },
  "Sunstrand Shoal": { index: "2316" },
  "Sunstrand Delta": { index: "2317" },
  "Dryvein Plain": { index: "2319" },
  "Farshore Esker": { index: "2320" },
  "Dryvein Oasis": { index: "2334" },
  "Sunstrand Dunes": { index: "2335" },
  "Farshore Heath": { index: "2336" },
  "Sunstrand Quicksands": { index: "2348" },
  "Battlebrae Peaks": { index: "3317" },
  "Stonelake Fields": { index: "3325" },
  "Stonelake Hillock": { index: "3336" },
  "Stonemouth Southbluff": { index: "3358" },
  "Frostspring Passage": { index: "4336" },
  "Frostspring Volcano": { index: "4351" },
  "Whitewall Ridge": { index: "4352" },
  "Whitewall Pass": { index: "4359" },
  "Runnelvein Slough": { index: "0311" },
  "Runnelvein Bog": { index: "0326" },
  "Runnelvein Sink": { index: "0341" },
  "Giantweald Copse": { index: "1310" },
  "Deepwood Gorge": { index: "1327" },
  "Giantweald Roots": { index: "1331" },
  "Deepwood Copse": { index: "1343" },
  "Giantweald Glade": { index: "1344" },
  "Eye of the Forest": { index: "1356" },
  Eldersleep: { index: "1357" },
  "Skylake Hinterlands": { index: "3339" },
  "Thunderrock Draw": { index: "3353" },
  "Floatshoal Floe": { index: "4313" },
  "Iceburn Firth": { index: "4318" },
  "Flammog Fork": { index: "4319" },
  "Iceburn Peaks": { index: "4328" },
  "Flammog Valley": { index: "4330" },
  "Iceburn Cliffs": { index: "4342" },
  "Iceburn Tundra": { index: "4346" },
  "Flammog Desolation": { index: "4354" },
  "Glacierfall Fissure": { index: "4356" },
  "Driprock Tunnel": { index: "PSG-0053#1" },
  "Shale Underway": { index: "PSG-0051#1" },
  "Smuggler's Rut": { index: "PSG-0052#1" },
  "Crosscut Skip": { index: "PSG-0038#2" },
  "Widemoor Delta": { index: "0317" },
  "Willowshade Mire": { index: "0318" },
  "Willowshade Lake": { index: "0319" },
  "Willowshade Icemarsh": { index: "0320" },
  "Widemoor Flats": { index: "0334" },
  "Willowshade Sink": { index: "0345" },
  "Widemoor Fen": { index: "0348" },
  "Twinchannel Narrows": { index: "0350" },
  "Unhallowed Cloister": { index: "0357" },
  "Westweald Thicket": { index: "1323" },
  "Driftwood Glen": { index: "1334" },
  "Westweald Shore": { index: "1351" },
  "Sandmount Strand": { index: "2312" },
  "Bleachskull Steppe": { index: "2314" },
  "Sandmount Esker": { index: "2318" },
  "Sandrift Steppe": { index: "2321" },
  "Sandrift Prairie": { index: "2322" },
  "Sandrift Coast": { index: "2323" },
  "Sandrift Shore": { index: "2324" },
  "Farshore Bay": { index: "2325" },
  "Bleachskull Desert": { index: "2333" },
  "Sandrift Expanse": { index: "2337" },
  "Farshore Lagoon": { index: "2338" },
  "Sandmount Desert": { index: "2349" },
  "Sandrift Dunes": { index: "2350" },
  "Farshore Drylands": { index: "2351" },
  "Sandrift Fringe": { index: "2352" },
  "Farshore Cape": { index: "2353" },
  "Sandmount Ascent": { index: "2358" },
  "Braemore Upland": { index: "3309" },
  "Windgrass Border": { index: "3318" },
  "Windgrass Gully": { index: "3320" },
  "Windgrass Rill": { index: "3321" },
  "Windgrass Precipice": { index: "3322" },
  "Braemore Lowland": { index: "3331" },
  "Windgrass Fields": { index: "3333" },
  "Windgrass Coast": { index: "3334" },
  "Highstone Mound": { index: "3346" },
  "Avalanche Ravine": { index: "4314" },
  "Frostbite Chasm": { index: "4316" },
  "Frostseep Ravine": { index: "4320" },
  "Frostbite Mountain": { index: "4335" },
  "Frostseep Crevasse": { index: "4347" },
  "Longfen Marsh": { index: "0322" },
  "Mudfoot Sump": { index: "0323" },
  "Mudfoot Mounds": { index: "0337" },
  "Longfen Veins": { index: "0352" },
  "Deathreach Priory": { index: "0359" },
  "Greenhollow Vale": { index: "1324" },
  "Greenhollow Copse": { index: "1352" },
  "Highstone Plains": { index: "3315" },
  "Battlebrae Flatland": { index: "3316" },
  "Highstone Grassland": { index: "3319" },
  "Gravemound Brim": { index: "3323" },
  "Gravemound Hills": { index: "3324" },
  "Gravemound Slope": { index: "3337" },
  "Battlebrae Meadow": { index: "3349" },
  "Windgrass Terrace": { index: "3350" },
  "Gravemound Knoll": { index: "3351" },
  "Gravemound Cliffs": { index: "3352" },
  "Highstone Loch": { index: "3357" },
  "Redtree Enclave": { index: "3359" },
  "Deathcap Channel": { index: "PSG-0052#2" },
  "Glowmire Grotto": { index: "PSG-0052#3" },
  "Lurkers' Hollow": { index: "PSG-0051#2" },
  "Middlemurk Path": { index: "PSG-0050#1" },
  "Craglight Cavern": { index: "PSG-0048#1" },
  "Deathwisp Sink": { index: "0346" },
  "Deathwisp Bog": { index: "0347" },
  "Sunkenbough Woods": { index: "0349" },
  "Black Monastery": { index: "0356" },
  "Sunkenbough Spring": { index: "0358" },
  "Rivercopse Crossing": { index: "1318" },
  "Driftwood Vale": { index: "1321" },
  "Hightree Borderlands": { index: "1333" },
  "Rivercopse Curve": { index: "1346" },
  "Driftwood Hollow": { index: "1348" },
  "Rivercopse Path": { index: "1349" },
  "Darkbough Snag": { index: "1358" },
  "Rivercopse Fount": { index: "1359" },
  "Sunfang Ravine": { index: "2310" },
  "Sunfang Approach": { index: "2330" },
  "Parchsand Cliffs": { index: "2331" },
  "Sunfang Cliffs": { index: "2343" },
  "Sunfang Wasteland": { index: "2344" },
  "Wailing Bulwark": { index: "2356" },
  "Sunfang Dawn": { index: "2357" },
  "Parchsand Drought": { index: "2359" },
  "Murdergulch Cross": { index: "3306" },
  "Murdergulch Gap": { index: "3307" },
  "Razorrock Passage": { index: "3308" },
  "Razorrock Valley": { index: "3310" },
  "Highstone Meadow": { index: "3311" },
  "Battlebrae Plain": { index: "3312" },
  "Battlebrae Lake": { index: "3313" },
  "Stonemouth Northbluff": { index: "3314" },
  "Thunderrock Rapids": { index: "3329" },
  "Razorrock Ravine": { index: "3330" },
  "Razorrock Edge": { index: "3332" },
  "Stonemouth Bay": { index: "3335" },
  "Thunderrock Ascent": { index: "3340" },
  "Thunderrock Upland": { index: "3341" },
  "Murdergulch Trail": { index: "3342" },
  "Razorrock Chasm": { index: "3343" },
  "Razorrock Verge": { index: "3344" },
  "Razorrock Bank": { index: "3345" },
  "Highstone Plateau": { index: "3347" },
  "Battlebrae Grassland": { index: "3348" },
  "Murdergulch Divide": { index: "3354" },
  "Murdergulch Ravine": { index: "3355" },
  "Razorrock Gulch": { index: "3356" },
  "Firesink Caldera": { index: "4333" },
  "Whitecliff Peak": { index: "4334" },
  "Firesink Trench": { index: "4349" },
  "Whitecliff Expanse": { index: "4350" },
  "Avalanche Incline": { index: "4358" },
  "Bedrock Passage": { index: "PSG-0051#3" },
  "Everglow Deep": { index: "PSG-0051#4" },
  "Longfen Arms": { index: "0336" },
  "Thirstwater Steppe": { index: "2311" },
  "Dryvein Riverbed": { index: "2313" },
  "Thirstwater Waste": { index: "2329" },
  "Dryvein Steppe": { index: "2332" },
  "Dryvein End": { index: "2345" },
  "Thirstwater Gully": { index: "2346" },
  "Dryvein Confluence": { index: "2347" },
  "Daemonium Keep": { index: "2360" },
  "Nightbloom Track": { index: "PSG-0004#1" },
  "Mudrock Burrow": { index: "PSG-0045#1" },
  "Deathcreep Adit": { index: "PSG-0053#2" },
  "Arthur's Rest": { index: "4300" },
  "Merlyn's Rest": { index: "1012" },
  "Conquerors' Hall Lvl. 1": { index: "4007-HALL-01" },
  "Conquerors' Hall Lvl. 2": { index: "4008-HALL-02" },
  "Morgana's Rest": { index: "0008" },
  "Ouyos-Aoeuam": { index: "TNL-001" },
  "Coues-Exakrom": { index: "TNL-002" },
  "Puros-Amayam": { index: "TNL-003" },
  "Pures-Ouozlum": { index: "TNL-004" },
  "Soros-Axaesum": { index: "TNL-005" },
  "Huyos-Uxeulum": { index: "TNL-006" },
  "Ceres-Iooinum": { index: "TNL-007" },
  "Cetos-Obaelos": { index: "TNL-008" },
  "Oieos-Umiutum": { index: "TNL-009" },
  "Sebos-Avoirom": { index: "TNL-010" },
  "Teros-Auiusum": { index: "TNL-011" },
  "Oebos-Ixakaum": { index: "TNL-012" },
  "Touos-Uoemtum": { index: "TNL-013" },
  "Xasos-Aeoilos": { index: "TNL-014" },
  "Xuros-Eyoztum": { index: "TNL-015" },
  "Pasos-Avosam": { index: "TNL-016" },
  "Oasos-Uromlum": { index: "TNL-017" },
  "Casos-Uruxtum": { index: "TNL-018" },
  "Ceros-Aeaylum": { index: "TNL-019" },
  "Xouos-Aioblos": { index: "TNL-020" },
  "Oasos-Eraerom": { index: "TNL-021" },
  "Tetos-Igaelum": { index: "TNL-022" },
  "Hynos-Oiaelos": { index: "TNL-023" },
  "Hebos-Ulamsum": { index: "TNL-024" },
  "Hiros-Iuaerom": { index: "TNL-025" },
  "Cynos-Avixnum": { index: "TNL-026" },
  "Conos-Avaelum": { index: "TNL-027" },
  "Tetos-Ulaurom": { index: "TNL-028" },
  "Oures-Araosum": { index: "TNL-029" },
  "Hures-Ugumtum": { index: "TNL-030" },
  "Hasos-Iuimaum": { index: "TNL-031" },
  "Foros-Egoisum": { index: "TNL-032" },
  "Hasos-Agoitum": { index: "TNL-033" },
  "Setos-Avamsum": { index: "TNL-034" },
  "Tonos-Obayam": { index: "TNL-035" },
  "Honos-Umayaum": { index: "TNL-036" },
  "Huyes-Ogozlum": { index: "TNL-037" },
  "Curos-Avulsum": { index: "TNL-038" },
  "Cebos-Avemlum": { index: "TNL-039" },
  "Hasos-Inayaum": { index: "TNL-040" },
  "Sasos-Egeylos": { index: "TNL-041" },
  "Coros-Aiayrom": { index: "TNL-042" },
  "Hiros-Exozlos": { index: "TNL-043" },
  "Tiros-Ouultum": { index: "TNL-044" },
  "Cases-Ugumlos": { index: "TNL-045" },
  "Fynes-Unavtum": { index: "TNL-046" },
  "Fetos-Aiaylos": { index: "TNL-047" },
  "Fouos-Agosaum": { index: "TNL-048" },
  "Huyos-Eyoztum": { index: "TNL-049" },
  "Poues-Unatam": { index: "TNL-050" },
  "Fouos-Amaurom": { index: "TNL-051" },
  "Suyos-Onaytum": { index: "TNL-052" },
  "Xasos-Oneulum": { index: "TNL-053" },
  "Oynos-Oyozam": { index: "TNL-054" },
  "Coros-Atinaum": { index: "TNL-055" },
  "Sasos-Oiozlum": { index: "TNL-056" },
  "Xynos-Oyogam": { index: "TNL-057" },
  "Cynos-Oxaeaum": { index: "TNL-058" },
  "Tynos-Atatlos": { index: "TNL-059" },
  "Firos-Enomaum": { index: "TNL-060" },
  "Hynes-Exemrom": { index: "TNL-061" },
  "Hebes-Ouaylos": { index: "TNL-062" },
  "Foues-Aeaosum": { index: "TNL-063" },
  "Xilos-Osayam": { index: "TNL-064" },
  "Casos-Ayosrom": { index: "TNL-065" },
  "Souos-Ososlos": { index: "TNL-066" },
  "Xebos-Emimsum": { index: "TNL-067" },
  "Oetos-Oyexlos": { index: "TNL-068" },
  "Xebos-Exostum": { index: "TNL-069" },
  "Tynos-Eyexrom": { index: "TNL-070" },
  "Casos-Aximam": { index: "TNL-071" },
  "Hasos-Ayousum": { index: "TNL-072" },
  "Fasos-Ayiotum": { index: "TNL-073" },
  "Pebos-Avosrom": { index: "TNL-074" },
  "Sases-Avuotum": { index: "TNL-075" },
  "Xases-Oxoulum": { index: "TNL-076" },
  "Hieos-Avaolum": { index: "TNL-077" },
  "Xasos-Aoemaum": { index: "TNL-078" },
  "Hasos-Osuorom": { index: "TNL-079" },
  "Oynos-Eramtum": { index: "TNL-080" },
  "Couos-Ayayaum": { index: "TNL-081" },
  "Siros-Obobrom": { index: "TNL-082" },
  "Souos-Umogaum": { index: "TNL-083" },
  "Cilos-Avioaum": { index: "TNL-084" },
  "Fonos-Aiugsum": { index: "TNL-085" },
  "Synos-Ayailos": { index: "TNL-086" },
  "Xiles-Aiavlum": { index: "TNL-087" },
  "Sases-Aoarsum": { index: "TNL-088" },
  "Casos-Aiagsum": { index: "TNL-089" },
  "Tieos-Ayoslum": { index: "TNL-090" },
  "Hieos-Aiigaum": { index: "TNL-091" },
  "Poros-Aiayrom": { index: "TNL-092" },
  "Cilos-Ofailos": { index: "TNL-093" },
  "Silos-Apenlum": { index: "TNL-094" },
  "Fynos-Alodrom": { index: "TNL-095" },
  "Firos-Ezatam": { index: "TNL-096" },
  "Firos-Osinsum": { index: "TNL-097" },
  "Soues-Uzurtum": { index: "TNL-098" },
  "Ooros-Ataltum": { index: "TNL-099" },
  "Hynes-Ieatun": { index: "TNL-100" },
  "Fuyes-Izohun": { index: "TNL-101" },
  "Xetos-Obursum": { index: "TNL-102" },
  "Oetos-Ofailos": { index: "TNL-103" },
  "Tynos-Igurlum": { index: "TNL-104" },
  "Puros-Ofavam": { index: "TNL-105" },
  "Setos-Aiaitum": { index: "TNL-106" },
  "Tynos-Uxavrom": { index: "TNL-107" },
  "Souos-Availos": { index: "TNL-108" },
  "Sebos-Ugersum": { index: "TNL-109" },
  "Peros-Aiataum": { index: "TNL-110" },
  "Pieos-Ofairom": { index: "TNL-111" },
  "Sieos-Ofugtum": { index: "TNL-112" },
  "Tasos-Iriglos": { index: "TNL-113" },
  "Tiros-Odoxlum": { index: "TNL-114" },
  "Xases-Ataglos": { index: "TNL-115" },
  "Oires-Oloblum": { index: "TNL-116" },
  "Firos-Aiavam": { index: "TNL-117" },
  "Heros-Atoyam": { index: "TNL-118" },
  "Petos-Aietam": { index: "TNL-119" },
  "Touos-Ataglos": { index: "TNL-120" },
  "Poros-Oconun": { index: "TNL-121" },
  "Honos-Oyezam": { index: "TNL-122" },
  "Fieos-Atezsum": { index: "TNL-123" },
  "Ooros-Ecunsum": { index: "TNL-124" },
  "Coros-Alieam": { index: "TNL-125" },
  "Couos-Opodam": { index: "TNL-126" },
  "Horos-Ohenlum": { index: "TNL-127" },
  "Files-Azazsum": { index: "TNL-128" },
  "Sasos-Abizaum": { index: "TNL-129" },
  "Fones-Opavun": { index: "TNL-130" },
  "Fiees-Ohohtum": { index: "TNL-131" },
  "Siros-Ofurlos": { index: "TNL-132" },
  "Oiros-Alaiam": { index: "TNL-133" },
  "Xiros-Aiairom": { index: "TNL-134" },
  "Silos-Oyarlum": { index: "TNL-135" },
  "Fonos-Oleraum": { index: "TNL-136" },
  "Fieos-Aiuttum": { index: "TNL-137" },
  "Filos-Abalam": { index: "TNL-138" },
  "Synos-Oyarlos": { index: "TNL-139" },
  "Febos-Acalun": { index: "TNL-140" },
  "Pieos-Eterrom": { index: "TNL-141" },
  "Feros-Oyuctum": { index: "TNL-142" },
  "Pynos-Opabrom": { index: "TNL-143" },
  "Foros-Uzazlum": { index: "TNL-144" },
  "Cieos-Atatlum": { index: "TNL-145" },
  "Huros-Atontum": { index: "TNL-146" },
  "Tonos-Aboysum": { index: "TNL-147" },
  "Hiles-Izizaum": { index: "TNL-148" },
  "Sebos-Oyohun": { index: "TNL-149" },
  "Cilos-Otatrom": { index: "TNL-150" },
  "Oasitos-Aoeuam": { index: "TNL-201" },
  "Curites-Exakrom": { index: "TNL-202" },
  "Petitos-Amayam": { index: "TNL-203" },
  "Pynites-Ouozlum": { index: "TNL-204" },
  "Suyitos-Axaesum": { index: "TNL-205" },
  "Honitos-Uxeulum": { index: "TNL-206" },
  "Cuyites-Iooinum": { index: "TNL-207" },
  "Cieitos-Obaelos": { index: "TNL-208" },
  "Oonitos-Umiutum": { index: "TNL-209" },
  "Siritos-Avoirom": { index: "TNL-210" },
  "Tuyitos-Auiusum": { index: "TNL-211" },
  "Oieitos-Ixakaum": { index: "TNL-212" },
  "Turitos-Uoemtum": { index: "TNL-213" },
  "Xouitos-Aeoilos": { index: "TNL-214" },
  "Xouitos-Eyoztum": { index: "TNL-215" },
  "Peritos-Avosam": { index: "TNL-216" },
  "Oynitos-Uromlum": { index: "TNL-217" },
  "Conitos-Uruxtum": { index: "TNL-218" },
  "Cebitos-Aeaylum": { index: "TNL-219" },
  "Xuyitos-Aioblos": { index: "TNL-220" },
  "Oebitos-Eraerom": { index: "TNL-221" },
  "Tebitos-Igaelum": { index: "TNL-222" },
  "Huritos-Oiaelos": { index: "TNL-223" },
  "Hynitos-Ulamsum": { index: "TNL-224" },
  "Hetitos-Iuaerom": { index: "TNL-225" },
  "Cetitos-Avixnum": { index: "TNL-226" },
  "Casitos-Avaelum": { index: "TNL-227" },
  "Tasitos-Ulaurom": { index: "TNL-228" },
  "Oynites-Araosum": { index: "TNL-229" },
  "Hilites-Ugumtum": { index: "TNL-230" },
  "Huritos-Iuimaum": { index: "TNL-231" },
  "Fynitos-Egoisum": { index: "TNL-232" },
  "Huyitos-Agoitum": { index: "TNL-233" },
  "Soritos-Avamsum": { index: "TNL-234" },
  "Tasitos-Obayam": { index: "TNL-235" },
  "Hasitos-Umayaum": { index: "TNL-236" },
  "Hynites-Ogozlum": { index: "TNL-237" },
  "Ceritos-Avulsum": { index: "TNL-238" },
  "Coritos-Avemlum": { index: "TNL-239" },
  "Heritos-Inayaum": { index: "TNL-240" },
  "Seritos-Egeylos": { index: "TNL-241" },
  "Cetitos-Aiayrom": { index: "TNL-242" },
  "Heritos-Exozlos": { index: "TNL-243" },
  "Tieitos-Ouultum": { index: "TNL-244" },
  "Cieites-Ugumlos": { index: "TNL-245" },
  "Fieites-Unavtum": { index: "TNL-246" },
  "Foritos-Aiaylos": { index: "TNL-247" },
  "Fynitos-Agosaum": { index: "TNL-248" },
  "Heritos-Eyoztum": { index: "TNL-249" },
  "Pirites-Unatam": { index: "TNL-250" },
  "Fonitos-Amaurom": { index: "TNL-251" },
  "Seritos-Onaytum": { index: "TNL-252" },
  "Xetitos-Oneulum": { index: "TNL-253" },
  "Oebitos-Oyozam": { index: "TNL-254" },
  "Casitos-Atinaum": { index: "TNL-255" },
  "Souitos-Oiozlum": { index: "TNL-256" },
  "Xebitos-Oyogam": { index: "TNL-257" },
  "Conitos-Oxaeaum": { index: "TNL-258" },
  "Turitos-Atatlos": { index: "TNL-259" },
  "Feritos-Enomaum": { index: "TNL-260" },
  "Hebites-Exemrom": { index: "TNL-261" },
  "Hurites-Ouaylos": { index: "TNL-262" },
  "Fynites-Aeaosum": { index: "TNL-263" },
  "Xoritos-Osayam": { index: "TNL-264" },
  "Cieitos-Ayosrom": { index: "TNL-265" },
  "Synitos-Ososlos": { index: "TNL-266" },
  "Xetitos-Emimsum": { index: "TNL-267" },
  "Oeritos-Oyexlos": { index: "TNL-268" },
  "Xoritos-Exostum": { index: "TNL-269" },
  "Tieitos-Eyexrom": { index: "TNL-270" },
  "Cetitos-Aximam": { index: "TNL-271" },
  "Hynitos-Ayousum": { index: "TNL-272" },
  "Fuyitos-Ayiotum": { index: "TNL-273" },
  "Petitos-Avosrom": { index: "TNL-274" },
  "Suyites-Avuotum": { index: "TNL-275" },
  "Xerites-Oxoulum": { index: "TNL-276" },
  "Hasitos-Avaolum": { index: "TNL-277" },
  "Xilitos-Aoemaum": { index: "TNL-278" },
  "Hilitos-Osuorom": { index: "TNL-279" },
  "Oiritos-Eramtum": { index: "TNL-280" },
  "Curitos-Ayayaum": { index: "TNL-281" },
  "Setitos-Obobrom": { index: "TNL-282" },
  "Sasitos-Umogaum": { index: "TNL-283" },
  "Cieitos-Avioaum": { index: "TNL-284" },
  "Fynitos-Aiugsum": { index: "TNL-285" },
  "Sonitos-Ayailos": { index: "TNL-286" },
  "Xonites-Aiavlum": { index: "TNL-287" },
  "Synites-Aoarsum": { index: "TNL-288" },
  "Cynitos-Aiagsum": { index: "TNL-289" },
  "Tetitos-Ayoslum": { index: "TNL-290" },
  "Hilitos-Aiigaum": { index: "TNL-291" },
  "Ponitos-Aiayrom": { index: "TNL-292" },
  "Conitos-Ofailos": { index: "TNL-293" },
  "Soritos-Apenlum": { index: "TNL-294" },
  "Firitos-Alodrom": { index: "TNL-295" },
  "Fynitos-Ezatam": { index: "TNL-296" },
  "Feritos-Osinsum": { index: "TNL-297" },
  "Suyites-Uzurtum": { index: "TNL-298" },
  "Ouritos-Ataltum": { index: "TNL-299" },
  "Hurites-Ieatun": { index: "TNL-300" },
  "Filites-Izohun": { index: "TNL-301" },
  "Xynitos-Obursum": { index: "TNL-302" },
  "Ouritos-Ofailos": { index: "TNL-303" },
  "Tonitos-Igurlum": { index: "TNL-304" },
  "Piritos-Ofavam": { index: "TNL-305" },
  "Soritos-Aiaitum": { index: "TNL-306" },
  "Tonitos-Uxavrom": { index: "TNL-307" },
  "Synitos-Availos": { index: "TNL-308" },
  "Sasitos-Ugersum": { index: "TNL-309" },
  "Puyitos-Aiataum": { index: "TNL-310" },
  "Pouitos-Ofairom": { index: "TNL-311" },
  "Suyitos-Ofugtum": { index: "TNL-312" },
  "Toritos-Iriglos": { index: "TNL-313" },
  "Tebitos-Odoxlum": { index: "TNL-314" },
  "Xurites-Ataglos": { index: "TNL-315" },
  "Oynites-Oloblum": { index: "TNL-316" },
  "Furitos-Aiavam": { index: "TNL-317" },
  "Hynitos-Atoyam": { index: "TNL-318" },
  "Pynitos-Aietam": { index: "TNL-319" },
  "Tilitos-Ataglos": { index: "TNL-320" },
  "Peritos-Oconun": { index: "TNL-321" },
  "Hynitos-Oyezam": { index: "TNL-322" },
  "Fasitos-Atezsum": { index: "TNL-323" },
  "Oeritos-Ecunsum": { index: "TNL-324" },
  "Casitos-Alieam": { index: "TNL-325" },
  "Cilitos-Opodam": { index: "TNL-326" },
  "Huyitos-Ohenlum": { index: "TNL-327" },
  "Fasites-Azazsum": { index: "TNL-328" },
  "Silitos-Abizaum": { index: "TNL-329" },
  "Febites-Opavun": { index: "TNL-330" },
  "Ferites-Ohohtum": { index: "TNL-331" },
  "Synitos-Ofurlos": { index: "TNL-332" },
  "Oouitos-Alaiam": { index: "TNL-333" },
  "Xoritos-Aiairom": { index: "TNL-334" },
  "Sasitos-Oyarlum": { index: "TNL-335" },
  "Fasitos-Oleraum": { index: "TNL-336" },
  "Fouitos-Aiuttum": { index: "TNL-337" },
  "Fynitos-Abalam": { index: "TNL-338" },
  "Suyitos-Oyarlos": { index: "TNL-339" },
  "Fuyitos-Acalun": { index: "TNL-340" },
  "Pilitos-Eterrom": { index: "TNL-341" },
  "Fasitos-Oyuctum": { index: "TNL-342" },
  "Piritos-Opabrom": { index: "TNL-343" },
  "Filitos-Uzazlum": { index: "TNL-344" },
  "Cynitos-Atatlum": { index: "TNL-345" },
  "Hebitos-Atontum": { index: "TNL-346" },
  "Tuyitos-Aboysum": { index: "TNL-347" },
  "Honites-Izizaum": { index: "TNL-348" },
  "Siritos-Oyohun": { index: "TNL-349" },
  "Cieitos-Otatrom": { index: "TNL-350" },
  "Corrupted Lair": { index: "CORRUPT-020" },
  "PSG-0038": { index: "PSG-0038" },
  "PSG-0039": { index: "PSG-0039" },
  "PSG-0042": { index: "PSG-0042" },
  "PSG-0044": { index: "PSG-0044" },
  "PSG-0045": { index: "PSG-0045" },
  "PSG-0048": { index: "PSG-0048" },
  "PSG-0049": { index: "PSG-0049" },
  "PSG-0050": { index: "PSG-0050" },
  "PSG-0051": { index: "PSG-0051" },
  "PSG-0052": { index: "PSG-0052" },
  "PSG-0053": { index: "PSG-0053" },
  "PSG-0054": { index: "PSG-0054" },
  "PSG-0008": { index: "PSG-0008" },
  "PSG-0009": { index: "PSG-0009" },
  "PSG-0010": { index: "PSG-0010" },
  "PSG-0011": { index: "PSG-0011" },
  "PSG-0012": { index: "PSG-0012" },
  "PSG-0013": { index: "PSG-0013" },
  "PSG-0014": { index: "PSG-0014" },
  "PSG-0015": { index: "PSG-0015" },
  "PSG-0016": { index: "PSG-0016" },
  "PSG-0017": { index: "PSG-0017" },
  "PSG-0018": { index: "PSG-0018" },
  "PSG-0019": { index: "PSG-0019" },
  "PSG-0020": { index: "PSG-0020" },
  "PSG-0021": { index: "PSG-0021" },
  "PSG-0022": { index: "PSG-0022" },
  "PSG-0023": { index: "PSG-0023" },
  "PSG-0024": { index: "PSG-0024" },
  "PSG-0025": { index: "PSG-0025" },
  "PSG-0026": { index: "PSG-0026" },
  "PSG-0027": { index: "PSG-0027" },
  "PSG-0028": { index: "PSG-0028" },
  "PSG-0029": { index: "PSG-0029" },
  "PSG-0030": { index: "PSG-0030" },
  "PSG-0031": { index: "PSG-0031" },
  "PSG-0032": { index: "PSG-0032" },
  "PSG-0033": { index: "PSG-0033" },
  "PSG-0034": { index: "PSG-0034" },
  "PSG-0035": { index: "PSG-0035" },
  "PSG-0036": { index: "PSG-0036" },
  "PSG-0037": { index: "PSG-0037" },
  "PSG-0040": { index: "PSG-0040" },
  "PSG-0041": { index: "PSG-0041" },
  "PSG-0043": { index: "PSG-0043" },
  "PSG-0046": { index: "PSG-0046" },
  "PSG-0047": { index: "PSG-0047" },
  "Quaent-Vynsum": { index: "TNL-151" },
  "Quaent-Al-Vynsum": { index: "TNL-351" },
  "Quaent-Tersis": { index: "TNL-152" },
  "Quaent-Al-Tersis": { index: "TNL-352" },
  "Quaent-Viesom": { index: "TNL-153" },
  "Quaent-Al-Viesom": { index: "TNL-353" },
  "Quatun-Nusas": { index: "TNL-154" },
  "Quatun-Et-Nusas": { index: "TNL-354" },
  "Quaent-Qintis": { index: "TNL-155" },
  "Quaent-Al-Qintis": { index: "TNL-355" },
  "Quatun-Odetum": { index: "TNL-156" },
  "Quatun-Et-Odetum": { index: "TNL-356" },
  "Quaent-Al-Odesum": { index: "TNL-157" },
  "Quaent-In-Odesum": { index: "TNL-357" },
  "Quaent-Al-Nusis": { index: "TNL-158" },
  "Quaent-In-Nusis": { index: "TNL-358" },
  "Qiient-Tersom": { index: "TNL-159" },
  "Qiient-In-Tersom": { index: "TNL-359" },
  "Qiient-Odesas": { index: "TNL-160" },
  "Qiient-Qi-Odesas": { index: "TNL-360" },
  "Qiient-Nutis": { index: "TNL-161" },
  "Qiient-In-Nutis": { index: "TNL-361" },
  "Qiient-Vyntum": { index: "TNL-162" },
  "Qiient-In-Vyntum": { index: "TNL-362" },
  "Qiient-Al-Odesum": { index: "TNL-163" },
  "Qiient-Si-Odesum": { index: "TNL-363" },
  "Qiient-Al-Vynsis": { index: "TNL-164" },
  "Qiient-Qi-Vynsis": { index: "TNL-364" },
  "Qiitun-Et-Vynsom": { index: "TNL-165" },
  "Qiitun-Si-Vynsom": { index: "TNL-365" },
  "Qiient-Al-Tersas": { index: "TNL-166" },
  "Qiient-Qi-Tersas": { index: "TNL-366" },
  "Qiitun-Vietis": { index: "TNL-167" },
  "Qiitun-Et-Vietis": { index: "TNL-367" },
  "Qiient-Et-Tertum": { index: "TNL-168" },
  "Qiient-Si-Tertum": { index: "TNL-368" },
  "Qiient-Qinsum": { index: "TNL-169" },
  "Qiient-Et-Qinsum": { index: "TNL-369" },
  "Qiient-Al-Viesis": { index: "TNL-170" },
  "Qiient-In-Viesis": { index: "TNL-370" },
  "Qiient-Al-Nusom": { index: "TNL-171" },
  "Qiient-Qi-Nusom": { index: "TNL-371" },
  "Qiient-Et-Nusas": { index: "TNL-172" },
  "Qiient-Si-Nusas": { index: "TNL-372" },
  "Qiient-Et-Odetis": { index: "TNL-173" },
  "Qiient-Sa-Odetis": { index: "TNL-373" },
  "Qiient-In-Odetum": { index: "TNL-174" },
  "Qiient-Oc-Odetum": { index: "TNL-374" },
  "Qiitun-Duosum": { index: "TNL-175" },
  "Qiitun-Al-Duosum": { index: "TNL-375" },
  "Qiient-Al-Qinsis": { index: "TNL-176" },
  "Qiient-In-Qinsis": { index: "TNL-376" },
  "Secent-Odesom": { index: "TNL-177" },
  "Secent-Qi-Odesom": { index: "TNL-377" },
  "Sectun-Tersas": { index: "TNL-178" },
  "Sectun-Et-Tersas": { index: "TNL-378" },
  "Secent-Al-Odetis": { index: "TNL-179" },
  "Secent-Si-Odetis": { index: "TNL-379" },
  "Secent-Vyntum": { index: "TNL-180" },
  "Secent-Et-Vyntum": { index: "TNL-380" },
  "Secent-Viesum": { index: "TNL-181" },
  "Secent-Al-Viesum": { index: "TNL-381" },
  "Secent-Et-Odesis": { index: "TNL-182" },
  "Secent-Sa-Odesis": { index: "TNL-382" },
  "Sectun-Qinsom": { index: "TNL-183" },
  "Sectun-In-Qinsom": { index: "TNL-383" },
  "Secent-Al-Qinsom": { index: "TNL-184" },
  "Secent-Qi-Qinsom": { index: "TNL-384" },
  "Sectun-Al-Vyntis": { index: "TNL-185" },
  "Sectun-In-Vyntis": { index: "TNL-385" },
  "Secent-Nutum": { index: "TNL-186" },
  "Secent-Al-Nutum": { index: "TNL-386" },
  "Secent-Al-Tersum": { index: "TNL-187" },
  "Secent-In-Tersum": { index: "TNL-387" },
  "Sectun-In-Odesis": { index: "TNL-188" },
  "Sectun-Oc-Odesis": { index: "TNL-388" },
  "Secent-Duosom": { index: "TNL-189" },
  "Secent-Al-Duosom": { index: "TNL-389" },
  "Secent-Et-Qinsas": { index: "TNL-190" },
  "Secent-Si-Qinsas": { index: "TNL-390" },
  "Setent-Vietis": { index: "TNL-191" },
  "Setent-Al-Vietis": { index: "TNL-391" },
  "Settun-Odetum": { index: "TNL-192" },
  "Settun-Et-Odetum": { index: "TNL-392" },
  "Setent-Nusum": { index: "TNL-193" },
  "Setent-Et-Nusum": { index: "TNL-393" },
  "Settun-Vynsis": { index: "TNL-194" },
  "Settun-Al-Vynsis": { index: "TNL-394" },
  "Settun-Tersom": { index: "TNL-195" },
  "Settun-Al-Tersom": { index: "TNL-395" },
  "Setent-Duosas": { index: "TNL-196" },
  "Setent-Al-Duosas": { index: "TNL-396" },
  "Setent-Qintis": { index: "TNL-197" },
  "Setent-Et-Qintis": { index: "TNL-397" },
  "Settun-Al-Odetum": { index: "TNL-198" },
  "Settun-In-Odetum": { index: "TNL-398" },
  "Setent-Al-Qinsum": { index: "TNL-199" },
  "Setent-In-Qinsum": { index: "TNL-399" },
  "Settun-Al-Nusis": { index: "TNL-200" },
  "Settun-In-Nusis": { index: "TNL-400" },
  CrystalRealmDebug: { index: "CrystalRealmDebug" },
  "Conquerors' Hall Lvl. 3": { index: "4009-HALL-1-4" },
  "Champions' Realm": { index: "ChampionsRealmLive" },
  VegAnimTest: { index: "VegAnimTest" },
  "Large Crystal Realm": { index: "CrystalRealm20v20" },
  "The Plains": { index: "HELLGATE-01-5v5-01-HRD" },
  "The Hill": { index: "HELLGATE-02-5v5-01-HRD" },
  "The Boneyard": { index: "HELLGATE-03-5v5-01-HRD" },
  "The Four Bridges": { index: "HELLGATE-04-5v5-01-HRD" },
  "The Traverse": { index: "HELLGATE-05-5v5-01-HRD" },
  "The Fortress": { index: "HELLGATE-06-5v5-01-HRD" },
  "The Pit": { index: "HELLGATE-07-5v5-01-HRD" },
  "The Courtyard": { index: "HELLGATE-08-5v5-01-HRD" },
  "The Tribunal": { index: "HELLGATE-09-5v5-01-HRD" },
  "The Citadel": { index: "HELLGATE-10-5v5-01-HRD" },
  "Murky Fen": { index: "0215" },
  "Fog Fen": { index: "0216" },
  "Drownhorse Basin": { index: "0217" },
  "Slithertail Marsh": { index: "0218" },
  "Wanderlure Basin": { index: "0219" },
  "Falsestep Marsh": { index: "0220" },
  "Darkground Swamp": { index: "0221" },
  "Anklesnag Mire": { index: "0222" },
  "Dusktree Swamp": { index: "0223" },
  Flynsdell: { index: "1216" },
  Pinecopse: { index: "1217" },
  "Deeproot Wood": { index: "1218" },
  Aspenwood: { index: "1220" },
  Spindlewood: { index: "1221" },
  "Owlsong Glen": { index: "1222" },
  "Nightbloom Forest": { index: "1223" },
  "Dryfield Meadow": { index: "2216" },
  "Sandgust Cleft": { index: "2217" },
  "Longshadow Plain": { index: "2218" },
  "Flatriver Trough": { index: "2219" },
  "Redstone Plain": { index: "2220" },
  "Flimmerair Steppe": { index: "2221" },
  "Goldshimmer Plain": { index: "2222" },
  "Kilmar Tor": { index: "3216" },
  "Carns Hill": { index: "3217" },
  "Brons Hill": { index: "3218" },
  "Felniks Hill": { index: "3219" },
  "Adrens Hill": { index: "3220" },
  "Garrow Fell": { index: "3221" },
  "Broken Fell": { index: "3222" },
  "Pen Fenair": { index: "4217" },
  "Cairn Drain": { index: "4218" },
  "Caulder Fissure": { index: "4219" },
  "Cairn Cloch": { index: "4220" },
  "Creag Dhor": { index: "4221" },
  "Creag Meagir": { index: "4222" },
  "Domhain Chasm": { index: "4223" },
  "Creag's Way": { index: "PSG-0006#1" },
  "Chasmlight Cave": { index: "PSG-0006#2" },
  "PSG-H-0001": { index: "PSG-H-0001" },
  "Boulder Deep": { index: "PSG-H-0001#1" },
  "PSG-H-0002": { index: "PSG-H-0002" },
  "Drystone Channel": { index: "PSG-H-0002#1" },
  "PSG-0001": { index: "PSG-0001" },
  "PSG-0002": { index: "PSG-0002" },
  "Stoneroot Caverns": { index: "DNG-KPR-02-MAIN-028" },
  "Cathedral of Light": { index: "DNG-MOR-01-MAIN-09" },
  "Chambers of Truth": { index: "DNG-MOR-01-SUB-09" },
  "Hallowed Crypt": { index: "DNG-UND-01-MAIN-009" },
  "Exalted Crypt": { index: "DNG-UND-01-MAIN-028" },
  "Hallowed Undercrypt": { index: "DNG-UND-01-SUB-009" },
  "Exalted Undercrypt": { index: "DNG-UND-01-SUB-028" },
  "Deepwood Enclave": { index: "DNG-KPR-01-MAIN-03" },
  "Trinity Hall": { index: "DNG-UND-02-MAIN-04" },
  "Conquerors' Hall Lvl. 4": { index: "4010-HALL-04" },
  "DNG-UND-01-MAIN-06": { index: "DNG-UND-01-MAIN-06" },
  "DNG-UND-01-SUB-06": { index: "DNG-UND-01-SUB-06" },
  "LEGACY-KEEPER-01": { index: "LEGACY-KEEPER-01" },
  "LEGACY-KEEPER-SOLO-01": { index: "LEGACY-KEEPER-SOLO-01" },
  "LEGACY-UNDEAD-01": { index: "LEGACY-UNDEAD-01" },
  "LEGACY-UNDEAD-02": { index: "LEGACY-UNDEAD-02" },
  "Heretic Cellar Network": { index: "DNG-HER-01-MAIN-05" },
  "Thetford Portal": { index: "0301" },
  "Lymhurst Portal": { index: "1301" },
  "Bridgewatch Portal": { index: "2301" },
  "Martlock Portal": { index: "3301" },
  "Fort Sterling Portal": { index: "4301" },
  "0302": { index: "0302" },
  "0303": { index: "0303" },
  "0304": { index: "0304" },
  Brecilien: { index: "5001" },
  "Brecilien Bank": { index: "5002" },
  "Brecilien Market": { index: "5003" },
  "ISLAND-PLAYER-MISTS-0001f": { index: "ISLAND-PLAYER-MISTS-0001f" },
  "Brecilien Weald": { index: "5100" },
  "Brecilien Copse": { index: "5101" },
  "Brecilien Grove": { index: "5102" },
  "Brecilien Thicket": { index: "5103" },
  "ISLAND-PLAYER-MISTS-0001a": { index: "ISLAND-PLAYER-MISTS-0001a" },
  "ISLAND-PLAYER-MISTS-0001b": { index: "ISLAND-PLAYER-MISTS-0001b" },
  "ISLAND-PLAYER-MISTS-0001c": { index: "ISLAND-PLAYER-MISTS-0001c" },
  "ISLAND-PLAYER-MISTS-0001d": { index: "ISLAND-PLAYER-MISTS-0001d" },
  "ISLAND-PLAYER-MISTS-0001e": { index: "ISLAND-PLAYER-MISTS-0001e" },
  "Mists Dungeon": { index: "DNG-MISTS-UND-WIP-01-01" },
  "Conquerors' Hall Lvl. 5": { index: "4011-HALL-05" },
  "3012-HALL-02": { index: "3012-HALL-02" },
  "ISLAND-PLAYER-FOREST-0001a": { index: "ISLAND-PLAYER-FOREST-0001a" },
  "ISLAND-PLAYER-FOREST-0001b": { index: "ISLAND-PLAYER-FOREST-0001b" },
  "ISLAND-PLAYER-FOREST-0001c": { index: "ISLAND-PLAYER-FOREST-0001c" },
  "ISLAND-PLAYER-FOREST-0001d": { index: "ISLAND-PLAYER-FOREST-0001d" },
  "ISLAND-PLAYER-FOREST-0001e": { index: "ISLAND-PLAYER-FOREST-0001e" },
  "ISLAND-PLAYER-FOREST-0001f": { index: "ISLAND-PLAYER-FOREST-0001f" },
  "ISLAND-PLAYER-HIGHLAND-0001a": { index: "ISLAND-PLAYER-HIGHLAND-0001a" },
  "ISLAND-PLAYER-HIGHLAND-0001b": { index: "ISLAND-PLAYER-HIGHLAND-0001b" },
  "ISLAND-PLAYER-HIGHLAND-0001c": { index: "ISLAND-PLAYER-HIGHLAND-0001c" },
  "ISLAND-PLAYER-HIGHLAND-0001d": { index: "ISLAND-PLAYER-HIGHLAND-0001d" },
  "ISLAND-PLAYER-HIGHLAND-0001e": { index: "ISLAND-PLAYER-HIGHLAND-0001e" },
  "ISLAND-PLAYER-HIGHLAND-0001f": { index: "ISLAND-PLAYER-HIGHLAND-0001f" },
  "ISLAND-PLAYER-MOUNTAIN-0001a": { index: "ISLAND-PLAYER-MOUNTAIN-0001a" },
  "ISLAND-PLAYER-MOUNTAIN-0001b": { index: "ISLAND-PLAYER-MOUNTAIN-0001b" },
  "ISLAND-PLAYER-MOUNTAIN-0001c": { index: "ISLAND-PLAYER-MOUNTAIN-0001c" },
  "ISLAND-PLAYER-MOUNTAIN-0001d": { index: "ISLAND-PLAYER-MOUNTAIN-0001d" },
  "ISLAND-PLAYER-MOUNTAIN-0001e": { index: "ISLAND-PLAYER-MOUNTAIN-0001e" },
  "ISLAND-PLAYER-MOUNTAIN-0001f": { index: "ISLAND-PLAYER-MOUNTAIN-0001f" },
  "ISLAND-PLAYER-CAERLEON-0001a": { index: "ISLAND-PLAYER-CAERLEON-0001a" },
  "ISLAND-PLAYER-CAERLEON-0001b": { index: "ISLAND-PLAYER-CAERLEON-0001b" },
  "ISLAND-PLAYER-CAERLEON-0001c": { index: "ISLAND-PLAYER-CAERLEON-0001c" },
  "ISLAND-PLAYER-CAERLEON-0001d": { index: "ISLAND-PLAYER-CAERLEON-0001d" },
  "ISLAND-PLAYER-CAERLEON-0001e": { index: "ISLAND-PLAYER-CAERLEON-0001e" },
  "ISLAND-PLAYER-CAERLEON-0001f": { index: "ISLAND-PLAYER-CAERLEON-0001f" },
  "ISLAND-PLAYER-STEPPE-0001a": { index: "ISLAND-PLAYER-STEPPE-0001a" },
  "ISLAND-PLAYER-STEPPE-0001b": { index: "ISLAND-PLAYER-STEPPE-0001b" },
  "ISLAND-PLAYER-STEPPE-0001c": { index: "ISLAND-PLAYER-STEPPE-0001c" },
  "ISLAND-PLAYER-STEPPE-0001d": { index: "ISLAND-PLAYER-STEPPE-0001d" },
  "ISLAND-PLAYER-STEPPE-0001e": { index: "ISLAND-PLAYER-STEPPE-0001e" },
  "ISLAND-PLAYER-STEPPE-0001f": { index: "ISLAND-PLAYER-STEPPE-0001f" },
  "ISLAND-PLAYER-SWAMP-0001a": { index: "ISLAND-PLAYER-SWAMP-0001a" },
  "ISLAND-PLAYER-SWAMP-0001b": { index: "ISLAND-PLAYER-SWAMP-0001b" },
  "ISLAND-PLAYER-SWAMP-0001c": { index: "ISLAND-PLAYER-SWAMP-0001c" },
  "ISLAND-PLAYER-SWAMP-0001d": { index: "ISLAND-PLAYER-SWAMP-0001d" },
  "ISLAND-PLAYER-SWAMP-0001e": { index: "ISLAND-PLAYER-SWAMP-0001e" },
  "ISLAND-PLAYER-SWAMP-0001f": { index: "ISLAND-PLAYER-SWAMP-0001f" },
};
